### ISSUE TITLE
"Access Denied Error, Please Contact Support" when authorising ringcentral app in hubspot

### ISSUE THREAD

**Issue by fbaddicts** [ringcentral/hubspot-embeddable-ringcentral-phone#118]
When I'm trying to authorise the ringcentral chrome widget inside of hubspot, I'm receiving a "access denied, contact support" error message. 

Any ideas?

**Comment by zxdong262** [comment]
Hi @fbaddicts,

You may login out everything, clear cache, and retry to see if it will work.

**Comment by zxdong262** [comment]
might be similar tohttps://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/issues/1

Are you using a non-US account?

**Comment by zxdong262** [comment]
@fbaddicts Are you using a developer account to login?

**Comment by zxdong262** [comment]
Hi @fbaddicts 

Can you try the new release? Used standalone app.

https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.4.3

**Comment by steliospapagrigoriou** [comment]
yeah this seems to be working now, thanks
