### ISSUE TITLE
Hubspot changed their contact view/Calling from contact view doesn't work anymore

### ISSUE THREAD

**Issue by steliospapagrigoriou** [ringcentral/hubspot-embeddable-ringcentral-phone#124]
Hubspot recently changed their contact view and the extension doesn't show "Call with ringcentral" at the contact view anymore. Check screenshots of new contact view bellow:

Main tab in Contact View-
<img width="1401" alt="screenshot 2019-02-22 at 12 43 47" src="https://user-images.githubusercontent.com/2800904/53243590-5168ca00-36a0-11e9-9725-531728b257cb.png">

Calls tab in Contact View-
<img width="1210" alt="screenshot 2019-02-22 at 12 49 49" src="https://user-images.githubusercontent.com/2800904/53243604-5ded2280-36a0-11e9-85f1-afd61cd361f1.png">

**Comment by zxdong262** [comment]
@steliospapagrigoriou Thank you for the feeback, I will make an upgrade about this.

**Comment by zxdong262** [comment]
@steliospapagrigoriou When you click `make a phone call` button, you can see the call with rc button

**Comment by LeisureZone** [comment]
I do not see this option either.

**Comment by zxdong262** [comment]
I can see the `Make a phone call` from your screenshot, the second screenshot @LeisureZone

**Comment by LeisureZone** [comment]
![crm rc call button missing screenshot](https://user-images.githubusercontent.com/47987811/53530863-ec094480-3ab6-11e9-8d15-54fcc3f1a154.PNG)

**Comment by LeisureZone** [comment]
Once you push the Make A Phone Call button, the RingCentral button is not appearing

**Comment by LeisureZone** [comment]
Also, for some reason the RingCentral Chome app has been signing me out randomly all day as well. You can see in the screenshot as well.  This actually just happened and this screenshot was taken right when you replied to this thread.

**Comment by zxdong262** [comment]
@LeisureZone Oh, about the button, seems a situation I have not seen, I will think about a solution for this, about random sign out, can you take screenshots of console when this happens.

**Comment by zxdong262** [comment]
@steliospapagrigoriou Have released new version, set the button new position. Let me what do you think, thank you for the feedback.
