### ISSUE TITLE
404 error when Authorizing HubSpot

### ISSUE THREAD

**Issue by LeisureZone** [ringcentral/hubspot-embeddable-ringcentral-phone#126]
I am using a PC and I am having that same issue. When I originally installed the desktop app (version 0.4.1), it authorized and displayed as an integrated desktop app in HubSpot. I had the ability to call from HubSpot on my desktop, but my contacts were never synced even though I enabled the 'Auto log calls' option. That has been the extent of my "integration" features. It has never automatically logged any calls, showed incoming calls from HubSpot as anything other than the phone number, or gave me access to the contacts activities through the desktop app.

After reading a few threads I saw that there was an updated version (0.4.2) so I tried installing that one as well and it did not work. I thought it may have been because I still have the older version of the extension active, so I removed it, and deactivated it in HubSpot thinking that when I added the extension again it may re appear in HubSpot but it didn't. I now have version (0.4.3) on my computer and it still will not authorize or show up in HubSpot under 'Integrations'.

Please Help, thank you.

**Comment by LeisureZone** [comment]
HERE IS THE MESSAGE:

404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

GitHub Status — @githubstatus

**Comment by zxdong262** [comment]
Fixed now, sorry, I forget about the redirect page is in gh-pages.

**Comment by LeisureZone** [comment]
Thank you for your help. The authorization works now and shows up in HubSpot.  Unfortunately, it does not log the calls made from the RingCentral button in HubSpot.  Do you know why that is?

**Comment by zxdong262** [comment]
@LeisureZone I am investigating this, can not reproduce yet.

**Comment by zxdong262** [comment]
@LeisureZone if you search the number in RC widgets panel, can you find the contact related?

**Comment by zxdong262** [comment]
@LeisureZone In history list, would it the history item shows right contact name?

**Comment by zxdong262** [comment]
Close it now, has been a while, feel free to submit another issue.
