### ISSUE TITLE
HubSpot has Calling SDK in Beta now

### ISSUE THREAD

**Issue by bjsvec** [ringcentral/hubspot-embeddable-ringcentral-phone#127]
I know you have put a lot of work into this, but I wanted to share this with you.  It seems it would ultimately be a better path for integration because is should not be browser dependent..

https://community.hubspot.com/t5/HubSpot-Ideas/Offer-integrations-with-other-calling-vendors/idc-p/256614#M30514

Best.

**Comment by zxdong262** [comment]
Thank you, I would check this.

**Comment by ndwilliams3** [comment]
Here's the repository. https://github.com/HubSpot/calling-extensions-sdk

**Comment by zxdong262** [comment]
Work on it now: https://github.com/ringcentral/ringcentral-integration-for-hubspot
