### ISSUE TITLE
Auto sync call log 

### ISSUE THREAD

**Issue by chunyao70** [ringcentral/hubspot-embeddable-ringcentral-phone#128]
How do I sync the call logs between Hubspot and RingCentral automatically?

**Comment by zxdong262** [comment]
In setting there is a auto call log setting, by default it is on, if you find it not working when it is on, let me know.

**Comment by chunyao70** [comment]
It is not working.  I turn it to on and change Hubspot to "authorize" and it is still not working.

**Comment by chunyao70** [comment]
The auto call log is not working:

[cid:image001.png@01D4D445.D3F75260]

From: Albert Chen
Sent: Monday, March 4, 2019 6:51 PM
To: ringcentral/hubspot-embeddable-ringcentral-phone <reply@reply.github.com>
Subject: RE: [ringcentral/hubspot-embeddable-ringcentral-phone] Auto sync call log (#128)

It is not working.  I turn it to on and change Hubspot to "authorize" and it is still not working.

**Comment by zxdong262** [comment]
@chunyao70 Can not see your image posted from email.

**Comment by chunyao70** [comment]
I have included the image as an attachment.  I did select Auto Call Logs but calls made from RingCentral are not being logged in HubSpot.

**Comment by zxdong262** [comment]
@chunyao70 Is the phone number belongs to contact in hubspot?

**Comment by chunyao70** [comment]
Yes.

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.4.7 I believe this will fix, can you try it?

@chunyao70

**Comment by chunyao70** [comment]
Will do.so.in the morning


-------- Original message --------

**Comment by zxdong262** [comment]
Close it now, feel free to reopen it or submit another one.
