### ISSUE TITLE
contacts no syncing and phone number not listed error

### ISSUE THREAD

**Issue by tgreen12** [ringcentral/hubspot-embeddable-ringcentral-phone#131]
on one PC when I auth to improt hubspot contacts the process doesn't transfer contacts.

Also when in contacts and you click the ringcentral phone to call the  message "no phone number listed for the contact" appears 

![image](https://user-images.githubusercontent.com/47835259/55352237-018ed700-5486-11e9-97a6-d6528e231937.png)

![image](https://user-images.githubusercontent.com/47835259/55352197-e91ebc80-5485-11e9-9cef-16ed06fc7491.png)

Thank you

**Comment by zxdong262** [comment]
Seems hubspot api do not work any more, need a full rewrite to solve it.

**Comment by zxdong262** [comment]
Thank you for the feedback and released new version, let me know how it works, fixed some known problems related to recent Hubspot api change:

- Support new UI
- Support custom X-User-Agent
- New Auth and data fetch methods
- Custom prefix

https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.5.0

**Comment by tgreen12** [comment]
Not all contacts transferred over with the new update. thanks for your work

**Comment by bjsvec** [comment]
I also see only a small set of HubSpot customers synced.  In addition, I am getting the web phone not available message even though another message states it registered successfully:

**Comment by zxdong262** [comment]
Hi @bjsvec @tgreen12 
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.5.1
Released new version, can you try this one?

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.5.3
Released new version @tgreen12 @bjsvec

**Comment by zxdong262** [comment]
Close it now, feel free to submit another one.
