### ISSUE TITLE
Call Logs does not show

### ISSUE THREAD

**Issue by jin-fhg** [ringcentral/hubspot-embeddable-ringcentral-phone#133]
Hello,

I am having an issue with the call logs not showing under the activities tab of the contact, but I am able to see them from the dialer. The message pop up shows up saying that the call log is sync to hubspot but when I click it to check the activities, the log does not show. Here is a sample video of the issue:
https://drive.google.com/file/d/12AA7pXhSLXJww8tGcJ2lyzLfG-iqKaSf/view?usp=sharing

Also , how do I disable the session time out when I login to the RingCentral dialer in Hubspot. I attached the console log in case you need it.

app.hubspot.com-1554230606847.txt

**Comment by jin-fhg** [comment]
Hello, 

I am having an issue with the call logs not showing under the activities tab of the contact, but I am able to see them from the dialer. The message pop up shows up saying that the call log is sync to hubspot but when I click it to check the activities, the log does not show. Here is a sample video of the issue:
https://drive.google.com/file/d/12AA7pXhSLXJww8tGcJ2lyzLfG-iqKaSf/view?usp=sharing

Also , how do I disable the session time out when I login to the RingCentral dialer in Hubspot. I attached the console log in case you need it. 

[app.hubspot.com-1554230606847.txt](https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/files/3035478/app.hubspot.com-1554230606847.txt)

**Comment by zxdong262** [comment]
@jin-fhg For the log not showing, might be hubspot data delay? I tested, it works, can try some other time to see if it works now?

@embbnux About session timeout, can you answer this one?

**Comment by zxdong262** [comment]
Hi @jin-fhg 
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.5.1
Released new version, can you try this one?

**Comment by jin-fhg** [comment]
Hello @zxdong262,
I tried the new version, but I am still having the same issue. I also noticed that when I access the Recent Activities of a contact person and go to the Hubspot tab, it only shows a loading icon.

**Comment by zxdong262** [comment]
can you post the console log?

**Comment by jin-fhg** [comment]
[app.hubspot.com-1554554534326.log](https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/files/3050455/app.hubspot.com-1554554534326.log)

Console Log attached.

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.5.2

Hi @jin-fhg , released new version to fix this, can you try this?

**Comment by zxdong262** [comment]
@jin-fhg https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.5.3

**Comment by zxdong262** [comment]
Another release, https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.5.4 now timeout time is 7 days.

**Comment by jin-fhg** [comment]
Hello @zxdong262,

**Comment by zxdong262** [comment]
@jin-fhg Thank you for the feedback, released new version, this should fix now.

https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.5.5

**Comment by jin-fhg** [comment]
Hello @zxdong262,

**Comment by bjsvec** [comment]
I am still not having good luck either.  I have been following the comments and installed 0.5.5 and do not get calls synced to Hubspot contacts even though I see the message that is synced sucessfully and a link to view the contact.

What formats and fields are supported for phone number?  I have tried phone and mobile fields with variations like +14155551212, (415) 555-1212, 4155551212.  

I have also noticed the call logs on the RC side take over 15 minutes to sync after completing a call.  I am not sure if this is an app issue or a general issue with RC.

Thanks for your continued efforts on this.  I am not getting signed out of RC or HS so that is a great improvement.

**Comment by jin-fhg** [comment]
Hello @zxdong262 
I am receiving a lot of feedback from the Hubspot customers with this integration, and most of them are having this issue.

**Comment by jin-fhg** [comment]
Hello @zxdong262 
I am receiving a lot of feedback from the Hubspot customers with this integration, and most of them are having this issue.

**Comment by zxdong262** [comment]
@jin-fhg @bjsvec Released a new version to support more event type.
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.5.6

And @jin-fhg, you mean the activities in RC widgets, right?

<img width="292" alt="Screen Shot 2019-04-12 at 9 35 23 AM" src="https://user-images.githubusercontent.com/1641949/56006211-8f7c8480-5d06-11e9-98b6-c310a758a175.png">

**Comment by zxdong262** [comment]
@bjsvec Do you mean the auto call log sync? If it takes 15 minutes to trigger, that is too long than expected, when I tested it, it may take seconds or a minute, never that long. So in your env, it always take that long, or just once?

**Comment by jin-fhg** [comment]
Hello @zxdong262, 
The activities in the RC widget shows nothing as well as the activity history of the contact even though I am receiving a prompt from Hubspot that the call log is synced. 
![call log synced](https://user-images.githubusercontent.com/49035508/56045566-0a2fb900-5d74-11e9-9f89-07e923f717c6.png)
![image](https://user-images.githubusercontent.com/49035508/56045584-0ef46d00-5d74-11e9-8e3a-824ed975c3c6.png)

**Comment by bjsvec** [comment]
@zxdong262 I don't really ever use the call log except for testing this.  It has been intermittent for me, but certainly not within the few seconds one would expect.  I'll keep an eye on it.

Can you explain a bit what format phone numbers might need to be in to be recognized?  I was wondering if that could be an issue.  In the mean time I am having the same issue as @jin-fhg

**Comment by zxdong262** [comment]
@bjsvec When you can see the phone number of the hubspot contact from RC widgets, then the phone number format is OK. Check https://www.npmjs.com/package/libphonenumber-js for supported phone number format, we use this module to do number check internally.

**Comment by jin-fhg** [comment]
Hello @zxdong262, 
Did you find anything yet? Is the path for the dist folder a possible cause of the issue? I actually saved mine in the Folder I created inside the Downloads Folder. Will that causes issues? Let me know your thoughts about this and thanks in advance.

**Comment by zxdong262** [comment]
@jin-fhg I think dist folder location does not matter. I will check this tomorrow.

**Comment by jin-fhg** [comment]
Hello @zxdong262, 
Please let me know what you can find today on this issue. I appreciate your help.

**Comment by zxdong262** [comment]
@jin-fhg I did not reproduce this, all works in my test account.

Can you share your har file in background page? make sure the log sync included.

<img width="885" alt="Screen Shot 2019-04-17 at 7 40 19 AM" src="https://user-images.githubusercontent.com/1641949/56250966-2d47c900-60e4-11e9-9928-4dad1cf79c6a.png">

You can send the file in email to me. zxdong@gmail.com

**Comment by jin-fhg** [comment]
Hello @zxdong262 
Here are the attached HAR and Console Log from the background page. 
[nkdmoognodbfhkodagljchgpahicapjn.txt](https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/files/3087365/nkdmoognodbfhkodagljchgpahicapjn.txt)
[nkdmoognodbfhkodagljchgpahicapjn-1555459350987.txt](https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/files/3087366/nkdmoognodbfhkodagljchgpahicapjn-1555459350987.txt)

**Comment by zxdong262** [comment]
@jin-fhg Thank you for the feedback! Released new version with fix.
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.5.7

**Comment by bjsvec** [comment]
I can confirm call logs update for me now.  Thank you.

I have a new problem that I cannot get rid of this error though.  I tried clearing caches, incognito mode, etc.  Can you help?

**Comment by zxdong262** [comment]
@bjsvec What error? Images in email can not show in github.

**Comment by bjsvec** [comment]
Sorry. https://imgur.com/PvdVNoa <https://imgur.com/PvdVNoa> is what I am fighting with.  It must be a Chrome setting, but I haven’t been able to find it.  Thanks.

**Comment by zxdong262** [comment]
![PvdVNoa](https://user-images.githubusercontent.com/1641949/56257753-f089cb00-60ff-11e9-9b59-bc4c03732c32.png)

@embbnux Any ideas about this?

**Comment by jin-fhg** [comment]
Thank you @zxdong262, I can see the logs now. I will continue to play with it and let you know if I have other questions. Also, about the error that @bjsvec is encountering, this seems to be a permission issue with  the Chrome Browser. You may try to go to the content settings of Chrome and allow this app to access the microphone and the sound. Make sure as well that the browser has a default microphone detected by the browser.

**Comment by embbnux** [comment]
@zxdong262 When our widget requires microphone permission for web phone in first time, chrome browser will popup permission setting in address bar. If user `blocks microphone` or `doesn't have microphone device`, we will have that notification.
User can also go to `chrome://settings/content/microphone` page to allow our widget to use microphone. 

![image](https://user-images.githubusercontent.com/7036536/56264602-95fd6880-6119-11e9-9ec8-725c4d28af32.png)

**Comment by bjsvec** [comment]
Thanks all.  The audio trouble was a VM hijacking my audio and threw me for a loop.  I look forward to putting the contact sync through more evaluation.

**Comment by jin-fhg** [comment]
Thank you so much @zxdong262 Call logs are now working as expected.

**Comment by TVI227** [comment]
Hello @zxdong262,

We are experiencing the same issue as jin fhg in the below post. We have the most recent update. 1.5.1. We would appreciate any advice you can offer. Have tried syncing and unsyncing multiple times, the contacts in the RC widget and Hubspot are not showing any log of the calls. The call list is not attributing the call to the contact even tho they are in the widget. I have zero knowledge of programming, if you require any further information please provide simple instructions to obtain it.

Thank you 

> Hello @zxdong262,
> The activities in the RC widget shows nothing as well as the activity history of the contact even though I am receiving a prompt from Hubspot that the call log is synced. What could be the cause of this issue?
> ![call log synced](https://user-images.githubusercontent.com/49035508/56045566-0a2fb900-5d74-11e9-9f89-07e923f717c6.png)
