### ISSUE TITLE
The Sync Call Log to Hubspot

### ISSUE THREAD

**Issue by SeaFist** [ringcentral/hubspot-embeddable-ringcentral-phone#136]
Where can I retrieve in Hubpot the "Sync Call Log to Hubspot" for calls and descriptions created in embedded RingCentral dialer?

**Comment by zxdong262** [comment]
A detailed description about auto call log: https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/137

**Comment by zxdong262** [comment]
Close it now, feel free to submit another one.
