### ISSUE TITLE
About auto call log sync

### ISSUE THREAD

**Issue by zxdong262** [ringcentral/hubspot-embeddable-ringcentral-phone#137]
# About Auto call log sync feature

1. Make sure you have auto call log on in settings. And already authorized to access hubspot contacts data.
<img width="304" alt="Screen Shot 2019-05-02 at 8 21 55 AM" src="https://user-images.githubusercontent.com/1641949/57051418-024ca000-6cb4-11e9-829e-a29f232e0e99.png">

2. Make sure the call log is from or to hubspot contact, you can check this from call history panel, it must show correct contact name from hubspot contact. If it shows only phone number, even the number is from Hubspot contact, it will not sync to hubspot, maybe you did not sync the contacts data to RC integration, you can check from contacts from contact list, if not synced, you can unauth and reauth again to resync contacts or click the reload contacts icon in left bottom corner.

<img width="302" alt="Screen Shot 2019-05-02 at 8 22 53 AM" src="https://user-images.githubusercontent.com/1641949/57051632-00371100-6cb5-11e9-8ae7-e6e33f5a1c58.png">
<img width="303" alt="Screen Shot 2019-05-02 at 8 23 51 AM" src="https://user-images.githubusercontent.com/1641949/57051652-104ef080-6cb5-11e9-8fa8-e55b69ee60fb.png">
<img width="792" alt="Screen Shot 2019-05-02 at 8 35 13 AM" src="https://user-images.githubusercontent.com/1641949/57051718-5f952100-6cb5-11e9-86fe-3ecea2583339.png">

**Comment by tgreen12** [comment]
If I try to call someone from my Tasks list it says no phone number is associated with this contact even though you can call the same person/number from the app.

**Comment by cpopovec** [comment]
Is there an ability to give users access to only a select number of clients to call from the RingCentra extension?  my team's HubSpot has close to 200,000 contacts but I have 12 different teams that will be working in HubSpot and I only want members of certain teams to have access to just a select number of these 200,000 clients and not all of them
