### ISSUE TITLE
Error when syncing contacts

### ISSUE THREAD

**Issue by zwardfmg** [ringcentral/hubspot-embeddable-ringcentral-phone#138]
When attempting to sync contacts, I see it error out for a split second. It is attempting to import almost 37,000 contacts - is there anyway to get around this?

**Comment by zxdong262** [comment]
I will try to find a way handle this much contacts, Thank you for the feedback.

**Comment by zxdong262** [comment]
Hi zwardfmg

Release a new version, syncing contacts in background process.
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.5.11

Can you try this?

**Comment by zxdong262** [comment]
Close it now, feel free to submit another one.
