### ISSUE TITLE
desktop.ini files causing issues in Chrome Extensions

### ISSUE THREAD

**Issue by advancify** [ringcentral/hubspot-embeddable-ringcentral-phone#139]
Just installed webroot security and it immediately deleted this extension. I re-downloaded the extension and tried to upload the unpacked file and it said there are desktop.ini files inside the folder uploaded. If you delete the hidden desktop.ini files and re-upload, chrome takes it without a hitch.

Awesome extension, thanks for creating this!

[dist.zip](https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/files/3167760/dist.zip)

**Comment by zxdong262** [comment]
Thank you! I checked, in mac it do not have desktop.ini, seems windows auto add the desktop.ini file to the folder, I google it, got this https://www.computerhope.com/issues/ch001060.htm, not sure there is a way to avoid this(except publishing to Chrome store).

**Comment by advancify** [comment]
That makes sense. The desktop.ini files were preventing the extension from
installing.

Chrome has been warning me about this developer app loading in my browser,
any ideas why?

**Comment by zxdong262** [comment]
@advancify I guess it is because it is not published to Chrome store or your safe setting is more strict.

**Comment by zxdong262** [comment]
Close it now, feel free to submit another one.
