### ISSUE TITLE
Not available in "Deal" section of HubSpot

### ISSUE THREAD

**Issue by JasonIFI** [ringcentral/hubspot-embeddable-ringcentral-phone#143]
After installing this app, the RingCentral call option is available while viewing all Contacts and while viewing an individual Contact record in HubSpot. But it's not available in the "Deal" section of HubSpot where we want to call from.

**Comment by zxdong262** [comment]
Thank you for the feedback, I will add this, maybe next week.

**Comment by zxdong262** [comment]
@JasonIFI https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.6.1
Now it support call log sync to deal and add click-to-call button to deal page.

**Comment by zxdong262** [comment]
Close, feel free to reopen it or open new thread, thank you for the feedback.
