### ISSUE TITLE
Call Queue Feature Request

### ISSUE THREAD

**Issue by zwardfmg** [ringcentral/hubspot-embeddable-ringcentral-phone#144]
Currently, there is no Call Logging or Recording available when using the Call Queue feature - is it possible to allow end users to use Call Queues while still having calls automatically recorded?

**Comment by zxdong262** [comment]
@embbnux

**Comment by embbnux** [comment]
@zwardfmg Do you mean logging call that answered in other extension user? If the extension user that answered the call is using this hubspot extension, the call should be logged.

**Comment by zxdong262** [comment]
Close it now, feel free to reopen or submit another one, Feedbacks are always welcome.
