### ISSUE TITLE
Phone number not loading when using application

### ISSUE THREAD

**Issue by ennaillek** [ringcentral/hubspot-embeddable-ringcentral-phone#146]
When clicking the phone icon from within hubspot, the application pops up and phone number loads for a split second but then goes away.  The text icon works perfectly.  Anyone else having this issue?
![image](https://user-images.githubusercontent.com/52462640/60527687-537b0f00-9cb8-11e9-82ca-7aa352a44f84.png)

**Comment by zxdong262** [comment]
@ennaillek Hi, I tried, it works, so are you using the latest release?

**Comment by ennaillek** [comment]
Hi there,
I have tried on 5.11 and 6.1.   In effect, the calling doesn’t trigger.  The phone number pops up, tries to initiate the call and then goes away.  I am seeing these errors:

[cid:image001.png@01D53192.6FF26340]

**Comment by zxdong262** [comment]
@ennaillek Can not see images from email.

**Comment by zxdong262** [comment]
Close it now, feel free to submit another one.
