### ISSUE TITLE
Add more detail to call log

### ISSUE THREAD

**Issue by zxdong262** [ringcentral/hubspot-embeddable-ringcentral-phone#147]
![image](https://user-images.githubusercontent.com/1641949/60929495-2a740300-a2e4-11e9-9eea-c6a75649a52f.png)

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.7.0

**Comment by dnorb2019** [comment]
Thanks, @zxdong262 .

**Comment by SethBasenet** [comment]
@zxdong262 thanks for the update, I have been speaking with David at ringcentral and i was wondering is there a way to update another feature. Basically when i make a call using ringcentral its updating the contact, which is great, but it is at the same time not updating the company for which the contact is under. so when my sales reps are reaching out to these contacts at companies and calling them. Hubspot/ringcentral is only updating/adding an activity for the person not the company. Example shown below with screenshots attached. 

Testytesty is the company and Marty Mcfly is the contact who works at the company. i logged a call with your new extension the other day and it recorded to the person but not the company. 


![Company Screenshot](https://user-images.githubusercontent.com/53097016/61559617-18a70400-aa38-11e9-80b2-c59651d72f7c.png)
![Contact Screenshot](https://user-images.githubusercontent.com/53097016/61559622-1b095e00-aa38-11e9-9129-e26cdf9dda44.png)

**Comment by zxdong262** [comment]
@SethBasenet Thank you for the feedback, seems can be done, maybe in a day or two.

**Comment by zxdong262** [comment]
@SethBasenet https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v1.0.0 Can you try this new release? Now it should sync to company

**Comment by SethBasenet** [comment]
Thats great ZXdong

another issue is that we are unable to use the ringcentral widget from the company page. if you look at the screenshots from the last issue on the customer page i am able to click the ringcentral button underneathe the person but not under the company...any luck with this?

**Comment by zxdong262** [comment]
@SethBasenet Sure, consider it done! Thank you the feedback!

**Comment by SethBasenet** [comment]
@zxdong262 you are the man

**Comment by SethBasenet** [comment]
Just let me know when you complete this please

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v1.1.0

Support company as contact and company list click to call, now you can search and check company in RingCentral widgets.

@SethBasenet

**Comment by SethBasenet** [comment]
@zxdong262 i dont see this working can you send me a screenshot from your side

**Comment by zxdong262** [comment]
@SethBasenet Here:

<img width="809" alt="Screen Shot 2019-07-26 at 7 58 25 AM" src="https://user-images.githubusercontent.com/1641949/61916496-5a293900-af7b-11e9-87e1-7d1aa91e966d.png">
<img width="302" alt="Screen Shot 2019-07-26 at 7 58 57 AM" src="https://user-images.githubusercontent.com/1641949/61916498-5a293900-af7b-11e9-966e-cc092097cdf0.png">
<img width="303" alt="Screen Shot 2019-07-26 at 7 59 09 AM" src="https://user-images.githubusercontent.com/1641949/61916499-5ac1cf80-af7b-11e9-9d21-1e63a30387ea.png">

**Comment by SethBasenet** [comment]
@zxdong262 i mean on this page
![Company Screenshot](https://user-images.githubusercontent.com/53097016/61953282-02430000-af84-11e9-9b68-f70a4735ff9b.png)

**Comment by zxdong262** [comment]
@SethBasenet Oh, I see, will do it next week.

**Comment by zxdong262** [comment]
@SethBasenet 
Done!
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v1.3.1

**Comment by SethBasenet** [comment]
Hey ZXdong

before i download it can you send me a screenshot of it

*Seth Krawitz  **| President*

* Direct: 484-344-5547*

*Cell: 215-565-6728*

*seth@basenetsystems.com <seth@basenetsystems.com>*

*Skype: Seth.Krawitz*

*Trilian: Seth.Krawitz*



*Basenet Systems LLC*

*960 Brook Road, **Unit 2*

*Conshohocken, PA - 19428*
[image: cid:image001.jpg@01D3BA2E.907205D0]

**Comment by zxdong262** [comment]
<img width="794" alt="Screen Shot 2019-07-30 at 3 21 30 PM" src="https://user-images.githubusercontent.com/1641949/62164011-291b8080-b34e-11e9-9dac-923f1df4aa11.png">

**Comment by SethBasenet** [comment]
wow that looks fantastic, is there a way for when i get an incoming call
for there to be a preview window that pops up for who is calling me. i have
seen it before on the hubspot side but not sure of its potential from your
side

*Seth Krawitz  **| President*

* Direct: 484-344-5547*

*Cell: 215-565-6728*

*seth@basenetsystems.com <seth@basenetsystems.com>*

*Skype: Seth.Krawitz*

*Trilian: Seth.Krawitz*



*Basenet Systems LLC*

*960 Brook Road, **Unit 2*

*Conshohocken, PA - 19428*
[image: cid:image001.jpg@01D3BA2E.907205D0]

**Comment by zxdong262** [comment]
@SethBasenet Yes, should popup a user info window when inbound call comes.

**Comment by SethBasenet** [comment]
i dont thank that is happening, can you test it from your side

*Seth Krawitz  **| President*

* Direct: 484-344-5547*

*Cell: 215-565-6728*

*seth@basenetsystems.com <seth@basenetsystems.com>*

*Skype: Seth.Krawitz*

*Trilian: Seth.Krawitz*



*Basenet Systems LLC*

*960 Brook Road, **Unit 2*

*Conshohocken, PA - 19428*
[image: cid:image001.jpg@01D3BA2E.907205D0]

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v1.3.3

A new release, fixed popup for company, can you try it?

@SethBasenet

**Comment by SethBasenet** [comment]
hey ZXdong

having an issue where none of the calls are being logged in hubspot, just
says that there is an error syncing the cll

*Seth Krawitz  **| President*

* Direct: 484-344-5547*

*Cell: 215-565-6728*

*seth@basenetsystems.com <seth@basenetsystems.com>*

*Skype: Seth.Krawitz*

*Trilian: Seth.Krawitz*



*Basenet Systems LLC*

*960 Brook Road, **Unit 2*

*Conshohocken, PA - 19428*
[image: cid:image001.jpg@01D3BA2E.907205D0]

**Comment by SethBasenet** [comment]
Hey, my extensions stopped logging calls

im also getting udpates for 1.3.7 which i downloaded

can you look into this why my calls are now not logging

*Seth Krawitz  **| President*

* Direct: 484-344-5547*

*Cell: 215-565-6728*

*seth@basenetsystems.com <seth@basenetsystems.com>*

*Skype: Seth.Krawitz*

*Trilian: Seth.Krawitz*



*Basenet Systems LLC*

*960 Brook Road, **Unit 2*

*Conshohocken, PA - 19428*
[image: cid:image001.jpg@01D3BA2E.907205D0]

**Comment by zxdong262** [comment]
@SethBasenet Sure, I will check this.

**Comment by zxdong262** [comment]
@SethBasenet I can reproduce this issue, can you provide the HAR log for me, here is a guide how to do it.

https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/154

**Comment by SethBasenet** [comment]
please see attached HAR file

*Seth Krawitz  **| President*

* Direct: 484-344-5547*

*Cell: 215-565-6728*

*seth@basenetsystems.com <seth@basenetsystems.com>*

*Skype: Seth.Krawitz*

*Trilian: Seth.Krawitz*



*Basenet Systems LLC*

*960 Brook Road, **Unit 2*

*Conshohocken, PA - 19428*
[image: cid:image001.jpg@01D3BA2E.907205D0]

**Comment by zxdong262** [comment]
@SethBasenet Email will not send attachment or image to github thread.

**Comment by zxdong262** [comment]
@SethBasenet You can send har file to my email drake.zhao@ringcentral.com

**Comment by SethBasenet** [comment]
i sent the file did you get it?

*Seth Krawitz  **| President*

* Direct: 484-344-5547*

*Cell: 215-565-6728*

*seth@basenetsystems.com <seth@basenetsystems.com>*

*Skype: Seth.Krawitz*

*Trilian: Seth.Krawitz*



*Basenet Systems LLC*

*960 Brook Road, **Unit 2*

*Conshohocken, PA - 19428*
[image: cid:image001.jpg@01D3BA2E.907205D0]

**Comment by zxdong262** [comment]
@SethBasenet Yes, I got the file, sorry, other things interrupt me, make me forgot about it, will analyze it now.

**Comment by zxdong262** [comment]
@SethBasenet Can not see any related api request in har log, so you save the har after call log, right? If so, the error may happens in other phase, maybe we could have a meeting to find out why.

**Comment by SethBasenet** [comment]
Could it be that I have downloaded other versions of the extension. Other
then the last one you sent me?

Please excuse any typos, as this was sent from my phone.

**Comment by zxdong262** [comment]
@SethBasenet Should not be that reason, you may test different version to confirm

**Comment by SethBasenet** [comment]
Can you send me the latest version you worked on? I'll go back to the
version

Please excuse any typos, as this was sent from my phone.

**Comment by zxdong262** [comment]
It is all in https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases

**Comment by SethBasenet** [comment]
1.3.8? That's what I'm using and it's not working

Please excuse any typos, as this was sent from my phone.

**Comment by SethBasenet** [comment]
any feedback drake?

*Seth Krawitz  **| President*

* Direct: 484-344-5547*

*Cell: 215-565-6728*

*seth@basenetsystems.com <seth@basenetsystems.com>*

*Skype: Seth.Krawitz*

*Trilian: Seth.Krawitz*



*Basenet Systems LLC*

*960 Brook Road, **Unit 2*

*Conshohocken, PA - 19428*
[image: cid:image001.jpg@01D3BA2E.907205D0]

**Comment by zxdong262** [comment]
@SethBasenet Can not see any related api request in har log, so you save the har after call log, right? If so, the error may happens in other phase, maybe we could have a meeting to find out why.

**Comment by SethBasenet** [comment]
I can do that aswell.  Also I used 1.3.3 and it works better any other
version after that isn't working

Please excuse any typos, as this was sent from my phone.

**Comment by zxdong262** [comment]
@SethBasenet Thank you, I will check 1.33+ changes first.

**Comment by SethBasenet** [comment]
Thanks I hope that info helps. 1.3.3 is working ok

Please excuse any typos, as this was sent from my phone.

**Comment by zxdong262** [comment]
@SethBasenet I checked the code, 1.34-1.38 would not break the function, should be all the same, and confirmed It works, I even test the firefox extension in chrome, it works too.

**Comment by SethBasenet** [comment]
Can you check 133 and 138 133 works and 134 doesnt

Please excuse any typos, as this was sent from my phone.

**Comment by zxdong262** [comment]
@SethBasenet 1.38 works for sure, just checked

**Comment by SethBasenet** [comment]
What can I send you to show you the issue

Please excuse any typos, as this was sent from my phone.

**Comment by zxdong262** [comment]
@SethBasenet open the background console first, then try to reproduce the issue, then save the har file, browser console errors if there are any.

**Comment by zxdong262** [comment]
Close it now, feel free to submit another one.

**Comment by SethBasenet** [comment]
Hello again

the new extension (1.7.1)  im using is not working, its barely logging any
calls at all to hubspot

*Seth Krawitz  **| President*

* Direct: 484-344-5547*

*Cell: 215-565-6728*

*seth@basenetsystems.com <seth@basenetsystems.com>*

*Skype: Seth.Krawitz*

*Trilian: Seth.Krawitz*



*Basenet Systems LLC*

*960 Brook Road, **Unit 2*

*Conshohocken, PA - 19428*
[image: cid:image001.jpg@01D3BA2E.907205D0]

**Comment by zxdong262** [comment]
Hi @SethBasenet 

Just back to work, can we have a meeting, anytime exclude 23:00PM~06:30AM UTC+8 timezone(Shanghai time), you can contact me through drake.zhao@ringcentral.com
