### ISSUE TITLE
Contact Layout

### ISSUE THREAD

**Issue by SeaFist** [ringcentral/hubspot-embeddable-ringcentral-phone#148]
![hubspot](https://user-images.githubusercontent.com/48298504/61012240-36c59200-a3b0-11e9-802b-54ad8bae0341.png)

When someone call me on RingCentral the contact window pops up in Hubspot but it sticks like 3/4 and show a few information.

I suggest to make the Note floating and centered on that frame. Make the contact all the way, instead of showing some parts of it since it can be closed.

Please see image  of problem

**Comment by zxdong262** [comment]
Will do, thank you for the suggestion.

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.7.0 Can you try this?

**Comment by maclay77** [comment]
Hi there! I am having this same issue. I updated to v0.7.0 Is there a way to get it to bee all the way across the screen? Or at the very least get it to where it doesn't cut off the information on the left-hand side of the contact info from HubSpot?
![screencapture-app-hubspot-reports-dashboard-4057774-sales-2019-07-11-13_35_09](https://user-images.githubusercontent.com/52797090/61072202-cd11ac00-a3e0-11e9-9efd-366730e4592e.png)
 I've attached a screenshot of what the update looks like.

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.7.1
A new release, now the popup is full width. You may try it.
@SeaFist @maclay77

**Comment by maclay77** [comment]
@zxdong262 thanks so much for your help. I tested the new update and it seems to have created a few more issues. 

1. whenever the searched for contact pops up you can't see the very top of the screen as it is covered by the orange "contact" bar. maybe there's a way to have the hubspot contact screen begin below the orange bar
2. when a call ends the full-screen slides left and becomes a 1/3 screen (see screenshot and video). i really like this actually! the only issue is there is not a horizontal scroll bar so I am unable to see the contact's information. wanted to see if a horizontal scroll could be added
3. whenever a call ends and the contact slides to 1/3 screen the ability to close the popup goes away, and the only way to get it to go away is to refresh the page. thinking something happened when working on the resizing

<img width="1440" alt="Screen Shot 2019-07-12 at 9 52 30 AM" src="https://user-images.githubusercontent.com/52797090/61134131-e96b2280-a48c-11e9-8484-5db225ef2251.png">

[hsrc1.mov.zip](https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/files/3386717/hsrc1.mov.zip)

**Comment by KevinExpress** [comment]
I am having the  same issues as maclay77
plus when i call comes in it does not pop any contact information only when you answer a call

**Comment by zxdong262** [comment]
@KevinExpress @maclay77 Sorry, will fix asap.

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.7.2

@maclay77 @KevinExpress Should fix now.

**Comment by zxdong262** [comment]
@KevinExpress Outbound call will not trigger popup, it is designed like this, suggested by some other user who think it is not needed since caller already know who he wants to call. But if you have your reason to enable it, please let me know.

**Comment by KevinExpress** [comment]
@zxdong262 Thank you for support in fixing the problem 
So far it working great if there are any problems will let you know

**Comment by maclay77** [comment]
I actually have one more request in regards to this. Is there a way to get the popup to open in a separate tab? The only issue with this layout is that it closes completely when the call ends and I lose the ability to finish editing or making notes for a contact.

**Comment by zxdong262** [comment]
@maclay77 https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v0.7.3 Removed the auto close.
