### ISSUE TITLE
RC call integration not working with call logging.

### ISSUE THREAD

**Issue by dfranklin72** [ringcentral/hubspot-embeddable-ringcentral-phone#150]
Frustratingly we are still manually recording calls as the RC integration does not seem to log any call details in HUBSPOT.

**Comment by zxdong262** [comment]
Hi @dfranklin72 Do you mean the auto call log feature not working? If so, can you check this article: https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/137, maybe it will solve your problem.

And do try the latest release. Let me know if you still have problem.

**Comment by dfranklin72** [comment]
Yes the auto log feature. I had a look through the article 137. It has made no difference. Even if i try and log the calls manually from the RC client they do not resister in Hubspot.

**Comment by zxdong262** [comment]
@dfranklin72 Sorry for the delay, hope we could have a meeting to find out why.

**Comment by zxdong262** [comment]
Closed, feel free to reopen if needed
