### ISSUE TITLE
Search for Companies

### ISSUE THREAD

**Issue by maclay77** [ringcentral/hubspot-embeddable-ringcentral-phone#151]
Hi there! This app has been very helpful for my company. The only issue I've had with it is that my business puts most of our information under _Companies_ instead of _Contacts_. I wanted to see if there was a way to have all the features this currently has but searches for companies instead of contacts?

**Comment by zxdong262** [comment]
Hi @maclay77, Can you provide more detail about this, I do not understand the feature you described, maybe some screenshots?

**Comment by maclay77** [comment]
@zxdong262 I was wondering if there was a way for this feature to search for Companies instead of Contacts? Right now the app pulls up a Contact from HubSpot. I wanted to see if there was a way for it to pull up a Company

**Comment by zxdong262** [comment]
Do you mean another company list or search company name, show all contacts in that company? @maclay77

**Comment by maclay77** [comment]
Search Company Name. It would be very similar to what it already does, but it brings up a _Company_

**Comment by zxdong262** [comment]
@maclay77 I understand it now, will do, maybe in a few days.

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v1.1.0

Support company as contact and company list click to call, now you can search and check company in RingCentral widgets.

**Comment by zxdong262** [comment]
Close it now, feel free to reopen it or create another issue, thank you for the feedback!
