### ISSUE TITLE
On the Contact Page

### ISSUE THREAD

**Issue by SeaFist** [ringcentral/hubspot-embeddable-ringcentral-phone#153]
Unable to call from the contact page.

![No Phone number for this Contact](https://user-images.githubusercontent.com/48298504/62665363-90ba7700-b9b1-11e9-86ed-46f706b23829.PNG)

Will be able to call customer after clicking on the contact and showing the customer contact information.

**Comment by zxdong262** [comment]
A new release with fix: https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v1.3.7 @SeaFist
