### ISSUE TITLE
Referring calls to new RingCentral Desktop App on Windows not working

### ISSUE THREAD

**Issue by tmuehlherr** [ringcentral/hubspot-embeddable-ringcentral-phone#158]
Hi, I had to re-install my computer, so I downloaded the new RingCentral desktop app from their website. 
(About RingCentral, Version: 19.8.1 (E. 2.0.14), Build: 1095 (rev. 666395a), Copyright © 2019 RingCentral, Inc.)
It's now looking different and has a variety of new features. 
I had your extension dialer configured to use the RingCentral desktop app to make outbound calls. It looks like it's still referring calls, but they are not actually dialing and connecting. 
Thanks, 
Thomas.

**Comment by zxdong262** [comment]
https://www.ringcentral.com/apps/rc-phone Can you try this one? Do you get a browser popup about opening RC app?

**Comment by zxdong262** [comment]
Close it now, feel free to reopen or submit another one, Feedbacks are always welcome.
