### ISSUE TITLE
Sound not working on calls

### ISSUE THREAD

**Issue by diademsports** [ringcentral/hubspot-embeddable-ringcentral-phone#159]
I have the latest update, and since my issue with the WHITE screen was fixed I have not been able to hear calls in my head set.  I hear when I dial... so when I push a button to call I hear the beep, but I do not hear ringing, and I do not hear the person on the other side.  They can hear me.  My headset is setup properly.

**Comment by zxdong262** [comment]
@diademsports I confirmed it works in my env with my headset. Can you confirm that you selected your headset as output device?
<img width="203" alt="Screen Shot 2019-09-05 at 9 32 40 AM" src="https://user-images.githubusercontent.com/1641949/64304897-2e5c9280-cfc0-11e9-89a4-c78aa1ae461c.png">

**Comment by diademsports** [comment]
I have several options on output, 4 of which are all the same just worded differently, and with all I can only hear when I push the numbers to dial a call there is beeps.  Strangely sometimes I do not hear those either.   None I hear the ringing or the person when they answer.  
![output devices](https://user-images.githubusercontent.com/51383281/64339179-69a39500-cfb1-11e9-9a73-8909557824ce.jpg)

**Comment by zxdong262** [comment]
@diademsports How about set use default device, and set output device from your OS's setting?

**Comment by diademsports** [comment]
I had the issue several times before and it would eventually go away when I messed with Output device. This time, which began over a week ago, I have tried every combo, and none work.   Default, Headset, etc.

**Comment by zxdong262** [comment]
@diademsports Can you try this in a different PC to see if it works?

**Comment by diademsports** [comment]
It does work on my colleagues computer, he has no issues as of now.   But
the head set also works fine on my PC with sounds, and the headset works
when paired to my cell phone.

Evan Specht
Director of Operations
Toll: 1.844.434.2336
Cell(w): 561.366.2738
Fax: 205.725.6609
www.diademsports.com
Pompano Beach, FL
Instagram: @diademsports <http://www.instagram.com/diademsports>

**Comment by zxdong262** [comment]
Close it now, feel free to reopen or submit another one, Feedbacks are always welcome.

**Comment by diademsports** [comment]
https://diademsports.com/products/court-burst

SPEED. STABILITY. CONFIDENCE.

=E2=80=8A

If you're ready to move better on court, start here.
Comfort that lasts. Support you can trust. Performance that keeps up.

[SHOP NOW](https://diademsports.com/products/court-burst)

TAKE A LOOK AT REAL REVIEWS

https://diademsports.com/products/court-burst

https://diademsports.com/products/court-burst?variant=3D42051144908882

https://diademsports.com/products/court-burst?variant=3D42051144646738

[Image of Diadem Court Burst](https://diademsports.myshopify.com/products/c=
ourt-burst)

[SHOP NOW](https://diademsports.myshopify.com/products/court-burst)

=E2=80=8A

[Pickleball](https://diademsports.com/pages/pickleball-homepage)
[Tennis](https://diademsports.com/pages/tennis-homepage)
[Shoes](https://diademsports.com/pages/shoes-homepage)

Apparel & Accessories

[Twitter](http://facebook.com/diademsports)
[Instagram](https://www.instagram.com/diademsports)
***@***.***)

Diadem Sports 200 Park Central Blvd S Suite 1 Pompano Beach, FL 33064
No longer want to receive these emails? [Unsubscribe](https://manage.kmail-=
lists.com/subscriptions/unsubscribe?a=3DXefiQY&c=3D01KF14Y2TQPSG9WNKHC3GZ9G=
W9&k=3Dee176779603a8c753b0dad250e5c8c02&m=3D01KJX29VM36VGRH5G4AXNQ44JV&r=3D=
01KJYYR708N5JNYFRE7RJP3PJJ).

**Comment by diademsports** [comment]
https://diademsports.com/products/court-burst

SPEED. STABILITY. CONFIDENCE.

=E2=80=8A

If you're ready to move better on court, start here.
Comfort that lasts. Support you can trust. Performance that keeps up.

[SHOP NOW](https://diademsports.com/products/court-burst)

TAKE A LOOK AT REAL REVIEWS

https://diademsports.com/products/court-burst

https://diademsports.com/products/court-burst?variant=3D42051144908882

https://diademsports.com/products/court-burst?variant=3D42051144646738

NOW AVAILABLE IN WIDE

https://diademsports.com/products/court-burst?variant=3D42051144646738

https://diademsports.com/products/court-burst?variant=3D42051144646738

[Image of Diadem Court Burst](https://diademsports.myshopify.com/products/c=
ourt-burst)

[SHOP NOW](https://diademsports.myshopify.com/products/court-burst)

=E2=80=8A

[Pickleball](https://diademsports.com/pages/pickleball-homepage)
[Tennis](https://diademsports.com/pages/tennis-homepage)
[Shoes](https://diademsports.com/pages/shoes-homepage)

Apparel & Accessories

[Twitter](http://facebook.com/diademsports)
[Instagram](https://www.instagram.com/diademsports)
***@***.***)

Diadem Sports 200 Park Central Blvd S Suite 1 Pompano Beach, FL 33064
No longer want to receive these emails? [Unsubscribe](https://manage.kmail-=
lists.com/subscriptions/unsubscribe?a=3DXefiQY&c=3D01KF14Y2TQPSG9WNKHC3GZ9G=
W9&k=3Dee176779603a8c753b0dad250e5c8c02&se=3Dreply%2Bamiax4iwwu7r7zlt64evev=
n3p2kqzevbnhhb2kela4%40reply.github.com&m=3D01KY2HM1HZMZXQS4G2GT274PD3&r=3D=
01KY2ZXZ7Y02KWRMPBCK8WW2G8).

**Comment by diademsports** [comment]
https://diademsports.com/products/court-burst

=E2=80=8A

TWO NEW COLORS. ONE COURT BURST.

=E2=80=8A

Cool and clear, or warm and bright. Court Burst arrives in two new colorway=
s. Same speed. Same feel. New look.You'll be kicking yourself if you miss t=
hese.

[PRE-ORDER NOW](https://diademsports.com/products/court-burst)

WHICH WILL YOU CHOOSE?

https://diademsports.com/products/court-burst?variant=3D42534083625042

[ARCTIC MIST](https://diademsports.com/products/court-burst?variant=3D42534=
083625042)

https://diademsports.com/products/court-burst?variant=3D42534135529554

[DESERT SUN](https://diademsports.com/products/court-burst?variant=3D425341=
35529554)

https://diademsports.com/products/court-burst?variant=3D42534083625042

https://diademsports.com/products/court-burst?variant=3D42534135529554

=E2=80=8A

[Pickleball](https://diademsports.com/pages/pickleball-homepage)
[Tennis](https://diademsports.com/pages/tennis-homepage)
[Shoes](https://diademsports.com/pages/shoes-homepage)

Apparel & Accessories

[Twitter](http://facebook.com/diademsports)
[Instagram](https://www.instagram.com/diademsports)
***@***.***)

Diadem Sports 200 Park Central Blvd S Suite 1 Pompano Beach, FL 33064
No longer want to receive these emails? [Unsubscribe](https://manage.kmail-=
lists.com/subscriptions/unsubscribe?a=3DXefiQY&c=3D01KF14Y2TQPSG9WNKHC3GZ9G=
W9&k=3Dee176779603a8c753b0dad250e5c8c02&se=3Dreply%2Bamiax4iwwu7r7zlt64evev=
n3p2kqzevbnhhb2kela4%40reply.github.com&m=3D01KZ4EY7BBZVCBAQXBC21A8GNQ&r=3D=
01KZ6H5KHHSENJVJ10XNSD8RE3).

**Comment by diademsports** [comment]
https://diademsports.com/products/court-burst

=E2=80=8A

PICK YOUR SIDE.
SHIPPING NOW.

=E2=80=8A

Cool and clear, or warm and bright. Court Burst arrives in two new colorway=
s. Same speed. Same feel. New look.You'll be kicking yourself if you miss t=
hese.

[ORDER NOW](https://diademsports.com/products/court-burst)

WHICH SIDE WILL YOU CHOOSE?

https://diademsports.com/products/court-burst?variant=3D42534083625042

[ARCTIC MIST](https://diademsports.com/products/court-burst?variant=3D42534=
083625042)

https://diademsports.com/products/court-burst?variant=3D42534135529554

[DESERT SUN](https://diademsports.com/products/court-burst?variant=3D425341=
35529554)

https://diademsports.com/products/court-burst?variant=3D42534083625042

https://diademsports.com/products/court-burst?variant=3D42534135529554

=E2=80=8A

[Pickleball](https://diademsports.com/pages/pickleball-homepage)
[Tennis](https://diademsports.com/pages/tennis-homepage)
[Shoes](https://diademsports.com/pages/shoes-homepage)

Apparel & Accessories

[Twitter](http://facebook.com/diademsports)
[Instagram](https://www.instagram.com/diademsports)
***@***.***)

Diadem Sports 200 Park Central Blvd S Suite 1 Pompano Beach, FL 33064
No longer want to receive these emails? [Unsubscribe](https://manage.kmail-=
lists.com/subscriptions/unsubscribe?a=3DXefiQY&c=3D01KF14Y2TQPSG9WNKHC3GZ9G=
W9&k=3Dee176779603a8c753b0dad250e5c8c02&se=3Dreply%2Bamiax4iwwu7r7zlt64evev=
n3p2kqzevbnhhb2kela4%40reply.github.com&m=3D01KZP05J5CW6SR7J1ZPZHXN64A&r=3D=
01KZRBYCYNBWB831RZ30NKJ8B3).

**Comment by diademsports** [comment]
https://diademsports.com/products/court-burst?variant=42051144646738

 

SPEED. STABILITY. CONFIDENCE.

If you're ready to move better on court, start here.
Comfort that lasts. Support you can trust. Performance that keeps up.

[SHOP NOW](https://diademsports.com/products/court-burst)

 

https://diademsports.com/products/court-burst

 

TAKE A LOOK AT REAL REVIEWS

https://diademsports.com/products/court-burst

https://diademsports.com/products/court-burst?variant=42051144908882

https://diademsports.com/products/court-burst?variant=42051144646738

[Image of Diadem Court Burst](https://diademsports.myshopify.com/products/court-burst)

[SHOP NOW](https://diademsports.myshopify.com/products/court-burst)

 

[Pickleball](https://diademsports.com/pages/pickleball-homepage)
[Tennis](https://diademsports.com/pages/tennis-homepage)
[Shoes](https://diademsports.com/pages/shoes-homepage)

Apparel & Accessories

[Twitter](http://facebook.com/diademsports)
[Instagram](https://www.instagram.com/diademsports)
***@***.***)

Diadem Sports 200 Park Central Blvd S Suite 1 Pompano Beach, FL 33064
No longer want to receive these emails? [Unsubscribe](https://manage.kmail-lists.com/subscriptions/unsubscribe?a=XefiQY&c=01KF14Y2TQPSG9WNKHC3GZ9GW9&k=ee176779603a8c753b0dad250e5c8c02&se=reply%2Bamiax4iwwu7r7zlt64evevn3p2kqzevbnhhb2kela4%40reply.github.com&m=01M34W4HY1AZSAKJFH73E5XDB9&r=01M3A0YVZE3CPZ4Z72NN9BME1W).
