### ISSUE TITLE
Call recording log location

### ISSUE THREAD

**Issue by akfurrer** [ringcentral/hubspot-embeddable-ringcentral-phone#160]
I want my recorded calls to be logged to the contact I called, and right now they're being logged to my company that I'm making the calls from. Is this something that I can change?

**Comment by zxdong262** [comment]
@akfurrer So the company has same number as the contact?

**Comment by akfurrer** [comment]
No, but our company is in Hubspot as a contact and the phone number is a Ring Central number. So when I use the RingCentral extension to call one our business contacts through Hubspot, I want the call recording to be in the activity of whichever contact I called. But instead, it logs it under our company's activity because that's the number that was used to call.

**Comment by zxdong262** [comment]
@akfurrer As I tested, it will be synced to the contact and the company's log, what is your situation?

**Comment by akfurrer** [comment]
The situation is that it's not syncing to the contact for me, it's only syncing to the company. And I need to know if there's something on my end I need to change or if this is something written into the extension.

**Comment by zxdong262** [comment]
@akfurrer I can not reproduce this issue, if you can have a meeting with me, maybe I can find out why.

**Comment by akfurrer** [comment]
Okay, how can we set up a meeting?

**Comment by zxdong262** [comment]
@akfurrer Just tell me your timezone and available time range, I will schedule the meeting and send you the meeting link.

**Comment by akfurrer** [comment]
@zxdong262 Sorry it's taken me awhile to respond. I'm in Eastern Standard Time, and I can do either Monday or Tuesday between 8:30 am and 6 pm.

**Comment by zxdong262** [comment]
@akfurrer I forget to mention email, please send your email address to drake.zhao@ringcentral.com so I will reply you the meeting link and calendar info.

**Comment by zxdong262** [comment]
Close it now, feel free to reopen or submit another one, Feedbacks are always welcome.
