### ISSUE TITLE
Contact issue

### ISSUE THREAD

**Issue by TheMeng** [ringcentral/hubspot-embeddable-ringcentral-phone#161]
I am having a problem with hubsopt contacts making it to my iphone app. They show up in the ring central extension but not the iphone app...any suggestions?

**Comment by zxdong262** [comment]
Hi @TheMeng 
It only works in browser, would not save Hubspot contacts to RingCentral database, but you could see call/sms history in mobile app.

**Comment by zxdong262** [comment]
Close it now, feel free to submit another one.
