### ISSUE TITLE
Contacts are loading as Company

### ISSUE THREAD

**Issue by jamisargent** [ringcentral/hubspot-embeddable-ringcentral-phone#163]
Contacts are pulling in but they are pulling in as company. 
<img width="286" alt="Screen Shot 2019-10-10 at 2 18 01 PM" src="https://user-images.githubusercontent.com/44704294/66595402-e4d80800-eb68-11e9-8492-388fe100a4d2.png">

**Comment by zxdong262** [comment]
@jamisargent Only companies, no other contacts in the list?

**Comment by jamisargent** [comment]
Yes, when you filter by Hubspot all the contacts show up like that.
Thank you,
~*Jami*

Jami Sargent, Chief of Staff
*FTR* | *Transportation Intelligence*
jsargent@ftrintel.com
Office: (812) 727-8307
Toll-Free Office: (888) 988-1699 x 50
www.FTRintel.com <http://www.ftrintel.com/>

**Comment by zxdong262** [comment]
Sorry for the delay, is the new version working? @jamisargent

**Comment by zxdong262** [comment]
Close it now, feel free to reopen it or submit another one. Feedbacks are always welcome.
