### ISSUE TITLE
Call Logging is not working

### ISSUE THREAD

**Issue by SeaFist** [ringcentral/hubspot-embeddable-ringcentral-phone#167]
[rcrecord_0.zip](https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/files/3745168/rcrecord_0.zip)

**Comment by SeaFist** [comment]
Hi @zxdong262,

[hubspot.zip](https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/files/3745191/hubspot.zip)

Hello. I would like to report this from a customer of mine that had problems with the Hubspot integration that it is not call logging. Please see the har file and the video recording attached on the case.

**Comment by SeaFist** [comment]
The Hubspot integration after installation was automatically authorized. Did unauthorize and authorized and still it did not do Call Log, saying that it did not found a contact associated with the phone number.

**Comment by jackoutthebox11** [comment]
I am the customer whose RingCentral integration is not logging calls in HubSpot that @SeaFist mentioned above. Hopefully someone can find a solution.

**Comment by zxdong262** [comment]
@jackoutthebox11 Hi, can you try the reload contacts button in contacts panel in RingCentral widgets.

<img width="317" alt="Screen Shot 2019-10-23 at 9 49 56 AM" src="https://user-images.githubusercontent.com/1641949/67349479-8fddbe00-f57a-11e9-8b17-28f84eaadd98.png">

**Comment by jackoutthebox11** [comment]
I'll try it right now

**Comment by jackoutthebox11** [comment]
I don't have the same refresh button that you have under my widget's contacts tab.
![image](https://user-images.githubusercontent.com/56888015/67349987-78211e00-f517-11e9-912f-dae2854988de.png)

**Comment by jackoutthebox11** [comment]
@zxdong262 I may have figured it out. What through me off in the screenshot above was the RingCentral Google Chrome extension. When I clicked the Ringcentral Embeddable I did have that refresh button you did. Test call was logged but not recorded. I assume that's a ringcentral account setting. hopefuly this continues to work. If one is to use this embeddable integration with Hubspot it seems that simultaneously using the other RingCentral Google Chrome extension is a bad idea. Thanks for your help to you and @SeaFist

**Comment by zxdong262** [comment]
@jackoutthebox11 Thank you for the feedback!

**Comment by SeaFist** [comment]
@jackoutthebox11 Thank you for confirmation. @zxdong262 Thank you always for the assistance.

**Comment by zxdong262** [comment]
Close it, feel free to reopen it or submit another one if needed.
