### ISSUE TITLE
SMS Messages no longer updating to hubspot

### ISSUE THREAD

**Issue by finertouch** [ringcentral/hubspot-embeddable-ringcentral-phone#168]
In previous versions, after sending an SMS message in a contact record, that conversation was recorded in the Notes area of hubspot.  This info no longer syncs with hubspot once sent with RingCentral.

**Comment by zxdong262** [comment]
Hi, @finertouch So you mean, when sms with RingCentral desktop app, the log do not sync with Hubspot, but if send SMS from browser extension, it will sync?

**Comment by finertouch** [comment]
It no longer syncs at all.  It worked up until a few days ago.  I did the update but it stopped working prior to that.  Thanks.

**Comment by zxdong262** [comment]
@finertouch Can you have a meeting with me so I can check the problem? If you can, you can send your available time and timezone to drake.zhao@ringcentral.com , I will set the meeting and send you the meeting link and time.

**Comment by KMagneti** [comment]
Hello, 

I just installed the chrome extension and have done several test SMS messages and nothing appears to be syncing with Hubspot.   We can see the activity in the text window but nothing is being recorded in the activity feed for the contact in HubSpot.   Please advise. 

THANK YOU! 

![RC HS 2](https://user-images.githubusercontent.com/13275391/72169917-39b83400-338d-11ea-830d-165b0d947212.jpg)
![RC HS 1](https://user-images.githubusercontent.com/13275391/72169929-3c1a8e00-338d-11ea-8da0-8dccaf4b32e3.jpg)

**Comment by zxdong262** [comment]
@KMagneti Have you turn on auto log in settings?

**Comment by KMagneti** [comment]
What or where are the auto login settings?


*karen waldon, marketing specialist*
*magneti.com <http://magneti.com> **| **719.330.1091| karen@magneti.com
<karen@magneti.com> *

**Comment by zxdong262** [comment]
@KMagneti 

<img width="308" alt="Screen Shot 2020-01-14 at 12 05 42 AM" src="https://user-images.githubusercontent.com/1641949/72271398-c864d380-3661-11ea-90a4-24ff78701aa4.png">

**Comment by KMagneti** [comment]
Perfect!  It works!  Thank you!



*karen waldon, marketing specialist*
*magneti.com <http://magneti.com> **| **719.330.1091| karen@magneti.com
<karen@magneti.com> *

**Comment by thekerbey** [comment]
Im experiencing the same issue today and I have auto syncing turned on.

**Comment by zxdong262** [comment]
@thekerbey Have you sync all contacts?

**Comment by thekerbey** [comment]
yes

**Comment by thekerbey** [comment]
yes

**Comment by zxdong262** [comment]
@thekerbey Can we have a meeting to check it? If you can, please send email with your available time and timezone to drake.zhao@ringcentral.com, I will send you the meeting link.

**Comment by zxdong262** [comment]
@thekerbey I think I might know it now, can you check call tab? In latest release, sms log synced to call log too, not in note any more.
