### ISSUE TITLE
Call log sync issue

### ISSUE THREAD

**Issue by zxdong262** [ringcentral/hubspot-embeddable-ringcentral-phone#172]
Hello @zxdong262,

We are experiencing the same issue as jin fhg in the below post. We have the most recent update. 1.5.1. We would appreciate any advice you can offer. Have tried syncing and unsyncing multiple times, the contacts in the RC widget and Hubspot are not showing any log of the calls. The call list is not attributing the call to the contact even tho they are in the widget. I have zero knowledge of programming, if you require any further information please provide simple instructions to obtain it.

Thank you 

> Hello @zxdong262,
> The activities in the RC widget shows nothing as well as the activity history of the contact even though I am receiving a prompt from Hubspot that the call log is synced. What could be the cause of this issue?
> ![call log synced](https://user-images.githubusercontent.com/49035508/56045566-0a2fb900-5d74-11e9-9f89-07e923f717c6.png)

> ![image](https://user-images.githubusercontent.com/49035508/56045584-0ef46d00-5d74-11e9-8e3a-824ed975c3c6.png)

_Originally posted by @TVI227 in https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/133#issuecomment-557354948_

**Comment by zxdong262** [comment]
@TVI227 Can we have a meeting, so I can confirm the problem, if you can, please send email to drake.zhao@ringcentral.com, with your available time next week, and timezone, I will schedule the meeting and send you meeting info.

**Comment by TVI227** [comment]
It appears to have fixed itself, apologies for wasting your time, perhaps it just needed more time to calibrate. you can close this

**Comment by zxdong262** [comment]
@TVI227 No problem at all, feel free to submit issues here, without users' feedbacks, this project would not go this far.
