### ISSUE TITLE
Hubspot not logging international Calls 

### ISSUE THREAD

**Issue by jin-fhg** [ringcentral/hubspot-embeddable-ringcentral-phone#173]
Hello @zxdong262 

I have noticed so far that the International Calls are not being recognized as contacts when we try to dial out from the Integrated RingCentral widget in Hubspot. Please see the video attached. Please skip to timestamp 3:34 of the video:

https://drive.google.com/file/d/17R8PVrnEZ4dQk_GvE56dww8llU0OpTAd/view?usp=sharing

**Comment by zxdong262** [comment]
@jin-fhg Have you try the region settings, you can set country there, then the phone number without country code will be auto prefix with the country code you selected when matching, but for phone numbers other than this country you selected, must have country code, or it will be prefix with the selected country code when trying matching.

**Comment by jin-fhg** [comment]
Hello @zxdong262 

When you say the Region Settings. do you mean this? 

![modified (7)](https://user-images.githubusercontent.com/49035508/69804222-083e3b80-1219-11ea-88e1-bec2c2ec07a7.png)

I was not able to select the country code of the Hubspot phone number that I am trying to dial here. Please let me know if I am looking at the right page.

**Comment by zxdong262** [comment]
@jin-fhg If you have number not from the region you selected, then the number must have country code.

**Comment by zxdong262** [comment]
@jin-fhg Are you using the latest release?

**Comment by jin-fhg** [comment]
Hello @zxdong262, 

Yes, I am using the latest release, and as you can see in the video, the numbers have an area code.

**Comment by zxdong262** [comment]
@jin-fhg Can we have a meeting? There could some error I do know. If you have can a meeting with me, please send you available time this week and timezone to drake.zhao@ringcentral.com

**Comment by jin-fhg** [comment]
Hello @zxdong262 
Can we do it tomorrow or on Wednesday at 7 AM EST?

**Comment by zxdong262** [comment]
@jin-fhg Sure, need to know your email so I can send you the meeting link

**Comment by jin-fhg** [comment]
Hello @zxdong262 

My email is eugene.flores@ringcentral.com and the affected customer's email is vlad2753575@gmail.com. Please schedule the meeting tomorrow. 

Thank you.

**Comment by jin-fhg** [comment]
Hello @zxdong262, 

I have documented the issues we found during the meeting. I hope this helps: 
1. Unable to log company record type
2. If the phone number does not have a + sign in the beginning, it dials out, but it does not log the call

Thank you again for your time earlier.

**Comment by jin-fhg** [comment]
Hello @zxdong262 
I have contacted the customer who is facing this issue to see if they have tried the latest release, but they still have the same issue.
