### ISSUE TITLE
Attempting to integrate Ring Central with Hubspot.   Completed the installation, however outbound calling defaults to the hubspot calling app.   I am looking as to how to disable hubspot calling so that the RC calling app is used instead by default.

### ISSUE THREAD

**Issue by Cbradish** [ringcentral/hubspot-embeddable-ringcentral-phone#174]

**Comment by zxdong262** [comment]
<img width="356" alt="Screen Shot 2019-12-24 at 8 21 35 AM" src="https://user-images.githubusercontent.com/1641949/71386097-7f070280-2626-11ea-851c-28fe44605f91.png">

Can you try set calling from browser?

**Comment by Cbradish** [comment]
Hi.  Its already set this way.

**Comment by zxdong262** [comment]
So if you click call with RingCentral button, will popup RingCentral app?
<img width="272" alt="Screen Shot 2019-12-24 at 8 41 19 AM" src="https://user-images.githubusercontent.com/1641949/71386506-52081f00-2629-11ea-89eb-bb44f30fa87c.png">

**Comment by zxdong262** [comment]
Oh, I see, yes the Hubspot calling button still use Hubspot default calling app, if you want to call with RingCentral, you need to click the Call with ringCentral button.
@Cbradish

**Comment by Cbradish** [comment]
This is what I have.    I am hoping that I can click the phone icon on a contact and have the RC app make the call?

(and also log the call).


[cid:image001.png@01D5B9CA.2773CAD0]




Christopher Bradish
  +1 786 300 2442 (c)
117 NE 1st Ave
    Miami, FL 33132
+1 305 239 9044
www.bellatera.com<http://www.bellatera.com>

[signature_1891107740]

Disclaimer:  The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorized to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful.

**Comment by zxdong262** [comment]
@Cbradish Currently no plan for that in the Chrome integration, we do not overide that, there is a WIP Hubspot integration that can do this: https://github.com/ringcentral/ringcentral-integration-for-hubspot, may be published in Hubspot's market place.

**Comment by Cbradish** [comment]
Hi I am using Firefox not chrome if that makes any difference.  ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zxdong262** [comment]
@Cbradish For Firefox, no difference.
