### ISSUE TITLE
SMS messages duplicate in the notes field

### ISSUE THREAD

**Issue by finertouch** [ringcentral/hubspot-embeddable-ringcentral-phone#175]
It seems that from time to time, the sms notes that are recorded in hubspot duplicate over and over.  They don't seem to go to the person multiple times but they appear in the CRM again and again.  Seems like it might be the same time that the app syncs.  Can you help?

**Comment by zxdong262** [comment]
@finertouch Yes, due to current API limit, it is a known issue.
