### ISSUE TITLE
Instance is obsolete, please use Connection. Refer - https://jsstore.net/tutorial/connection/

### ISSUE THREAD

**Issue by JMF2012** [ringcentral/hubspot-embeddable-ringcentral-phone#176]
![Screen Shot 2020-01-15 at 9 07 09 AM](https://user-images.githubusercontent.com/1633481/72440270-84afbe00-3776-11ea-89d5-b7e08fdc3652.png)

Hello, I'm getting this error when unpacking the dist folder and installing the ringcentral extension. Can you please help me? Thank you.

**Comment by zxdong262** [comment]
Can you try disable all other exts, and do it again? I can not reproduce this.

**Comment by JMF2012** [comment]
I have disabled all extensions, downloaded the dist folder and unpacked it
and then still get the error. I've attached the screenshots of the sequence
of events.

-- 
[image: Logo] <https://www.fundinggates.com/fg-receivables-manager/>

[image: Logo]
Jean-Marc Freuler
CEO

Funding Gates
Receivables Software | Powerful Analytics | Reduce DSO
www.fundinggates.com/free-trial

AuraRise
Trade Credit | Supply Chain Financing
www.aurarise.com

C: (917) 297-6366
O: (646) 502-5534
E: freuler@fundinggates.com

**Comment by zxdong262** [comment]
Have you enable developer mode?

**Comment by JMF2012** [comment]
yes
-- 
[image: Logo] <https://www.fundinggates.com/fg-receivables-manager/>

[image: Logo]
Jean-Marc Freuler
CEO

Funding Gates
Receivables Software | Powerful Analytics | Reduce DSO
www.fundinggates.com/free-trial

AuraRise
Trade Credit | Supply Chain Financing
www.aurarise.com

C: (917) 297-6366
O: (646) 502-5534
E: freuler@fundinggates.com

**Comment by zxdong262** [comment]
Can we have a meeting now?
@JMF2012

**Comment by JMF2012** [comment]
Sure, do you want to call me? My cell is +19172976366

-- 
[image: Logo] <https://www.fundinggates.com/fg-receivables-manager/>

[image: Logo]
Jean-Marc Freuler
CEO

Funding Gates
Receivables Software | Powerful Analytics | Reduce DSO
www.fundinggates.com/free-trial

AuraRise
Trade Credit | Supply Chain Financing
www.aurarise.com

C: (917) 297-6366
O: (646) 502-5534
E: freuler@fundinggates.com

**Comment by zxdong262** [comment]
@JMF2012 Send you the email, you can just click the meeting link

**Comment by zxdong262** [comment]
@JMF2012 Can you try it in another mac or PC in your company?

**Comment by JMF2012** [comment]
It works at my colleagues computer who has a mac

--
Jean-Marc Freuler
+1 9172976366

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v1.7.1 Should fix now. Thank you for the feedback.
