### ISSUE TITLE
RingCentral for Hubspot Unable to Launch 

### ISSUE THREAD

**Issue by jin-fhg** [ringcentral/hubspot-embeddable-ringcentral-phone#177]
We have a customer having issues with the RingCentral for Hubspot Integration where he is unable to launch the Extension and it shows an error on the extension settings. We tried reinstalling the package, but it did not help. I gathered the Console files for you since the HAR logs are empty.

**Comment by jin-fhg** [comment]
Attaching the files

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v1.7.1 Should fix now. Thank you for the feedback.
