### ISSUE TITLE
Syncing issue 

### ISSUE THREAD

**Issue by tjrmillward** [ringcentral/hubspot-embeddable-ringcentral-phone#179]
Cannot seem to get this to sync. It is saying contact doesnt exist and phone number matches exactly in both Mobile Phone Field and Phone Number Field. Any ideas?

**Comment by tjrmillward** [comment]
![Screenshot 2020-01-29 at 15 20 43](https://user-images.githubusercontent.com/60438114/73371420-941e2380-42ad-11ea-9d42-f9f5415da6cd.png)

**Comment by tjrmillward** [comment]
![Screenshot 2020-01-29 at 15 40 11](https://user-images.githubusercontent.com/60438114/73371486-a8622080-42ad-11ea-8650-fc00f74705f9.png)
Error message I get

**Comment by zxdong262** [comment]
Sorry for the delay, make sure you resync all contacts by click the reload button in widget's contact tab, after you addd new contact or change contact's number, and use the leatest release.


You can check the resync process from the video: https://youtu.be/MciDRtxx1VQ
@tjrmillward
