### ISSUE TITLE
Text message goes to wrong person

### ISSUE THREAD

**Issue by finertouch** [ringcentral/hubspot-embeddable-ringcentral-phone#180]
On occasion, when sending a text message, it also shows up under the phone number of a different person and shows as if it was sent.  So basically, it goes to more than one person even though only one person was chosen.

**Comment by zxdong262** [comment]
It will sync to all conacts with that phone number(from or to), can you confirm if the contacts have same phone number, including mobile phone.

**Comment by finertouch** [comment]
They do not have the same number

Harold Johnson
Finer Touch Entertainment
347.252.6225
www.finertouchent.com<http://www.finertouchent.com>

________________________________

**Comment by zxdong262** [comment]
@finertouch Is it that one have same number as sender's number, one has receiver's number?

**Comment by zxdong262** [comment]
Close it now, feel free to reopen or submit another one, Feedbacks are always welcome.
