### ISSUE TITLE
Maximum of 5 webphone ?

### ISSUE THREAD

**Issue by AminD006** [ringcentral/hubspot-embeddable-ringcentral-phone#182]
![image](https://user-images.githubusercontent.com/61065064/74562941-b795cf00-4f39-11ea-88b3-1c58c3a35065.png)

**Comment by AminD006** [comment]
I have an issue with the app, sometimes it shows this message and during up to 30 minutes it's impossible to call

**Comment by zxdong262** [comment]
You are using chrome right?

**Comment by AminD006** [comment]
Yes using Google Chrome.
--
Amin Djema

IT Manager

Sofdesk
+1-514-229-1105 <+1-514-823-8399>
amin@sofdesk.com <jimmy@sofdesk.com>
www.sofdesk.com
[image: facebook] <https://www.facebook.com/sofdesk/>
[image: twitter] <https://twitter.com/sofdesk>
[image: linkedin] <https://www.linkedin.com/company/sofdesk/>


Le ven. 14 févr. 2020 à 19:08, ZHAO Xudong <notifications@github.com> a
écrit :

**Comment by zxdong262** [comment]
Thank you for the feedback, should be fixed, but I do not have confirmed schedule for this.

**Comment by AminD006** [comment]
Thanks a lot !

**Comment by annajoin** [comment]
Hi, @zxdong262 a user on my team is getting this same issue today 9/20/21. is there a recommended fix?

![image](https://user-images.githubusercontent.com/91089998/134061792-40e8cc94-405a-4a3a-947a-c176d4324201.png)

**Comment by zxdong262** [comment]
Could close all pages running RingCentral widget, wait for some time, should fix then

**Comment by embbnux** [comment]
@annajoin Can you share app and browser version that the user is using? When user get this issue, he can logout and login to have it fixed.
