### ISSUE TITLE
1.8.7 and desktop app : Log issue

### ISSUE THREAD

**Issue by AminD006** [ringcentral/hubspot-embeddable-ringcentral-phone#183]
Hi,

when i use the desktop app with the plugin, in the call log it shows :
[Outbound Call connected] CALL from USERNAME1, USERNAME2, USERNAME3, USERNAME4.... (The list of ALL my Ringcentral users) to Destination user PhoneNumbers

**Comment by zxdong262** [comment]
That is because they have the same number - the calling number, you could choose a different number when calling.

**Comment by AminD006** [comment]
But we have different extensions.

**Comment by AminD006** [comment]
Issue fixed.
The caller was logging using the global phone number + ext. 
Now configured RC to use his direct phone number instead.
