### ISSUE TITLE
RC call integration not working with call logging since 1.8.7

### ISSUE THREAD

**Issue by AminD006** [ringcentral/hubspot-embeddable-ringcentral-phone#184]
No calls being logged since the update.
I went through the #137 with no success.
I rolled back to the 1.7.1 with no success :( 

Help please :/

**Comment by zxdong262** [comment]
Can you have a meeting with me, if so, please send an email to drake.zhao@ringcentral.com with your available time and timezone. I will shedule the meeting and send you the meeting link, so we check it, from myside, I can not reproduce the problem.
