### ISSUE TITLE
Call log/Contacts not syncing properly

### ISSUE THREAD

**Issue by grimeshine** [ringcentral/hubspot-embeddable-ringcentral-phone#186]
Im having a hell of a time trying to get my recent call section to associate phone numbers with my hubspot contacts. Some are working, but i find myself in a loop of unauthorizing/reuathorizing hubspot, relaunching the browser and other things to try and get the contacts to update so that I can log my call through the extension. Sometimes these things seem to work, sometimes it will even be a day or 2 later and I still wont see the contact associated with the phone number

**Comment by zxdong262** [comment]
@grimeshine Please check the video to see how it works: https://www.youtube.com/watch?v=MciDRtxx1VQ&feature=youtu.be, if still have problems, we can have a meeting to check it, you can send email to drake.zhao@ringcentral.com, with you available time range and timezone.

**Comment by tohagan** [comment]
I'm experiencing the same. I've watched your video and setup correctly. I found that it contact sycning works fine for small numbers of contacts in an account but for an account with large numbers it fails to sync them all - so probably you're hitting a HS API limit of some kind.

**Comment by zxdong262** [comment]
Please try the latest release, and wait for all contacts syned.
