### ISSUE TITLE
Not working in Queues and not syncing due to area code

### ISSUE THREAD

**Issue by AndrewArbuckle** [ringcentral/hubspot-embeddable-ringcentral-phone#187]
The Ringcentral icon disappears when using Queues for sales tasks so I can't call directly from hubspot without copying / pasting the number.  It reappears if just in a customer account without queue.

The phone number doesn't sync due to area code.  Example:
All mobile phone numbers are loaded in hubspot without area code, ie 0404999999, after making a call the ringcentral app prompts to add a new contact to hubspot as it doesn't recognise the number it just dialed, it has added the country code +61 404 999 999.

**Comment by zxdong262** [comment]
Make sure you add "+" for country code, +xx xxxxxxx works, xx xxxxxxx do not work.
