### ISSUE TITLE
Repeatedly fetching companies from HubSpot

### ISSUE THREAD

**Issue by tohagan** [ringcentral/hubspot-embeddable-ringcentral-phone#190]
I'm testing v1.11.0

The extension is calling this API every few seconds which is probably not acceptable to HubSpot if we have multiple users logged in.

`https://api.hubspot.com/companies/v2/companies/paged?portalId=<number>&clienttimeout=60000&limit=250&properties=name&properties=phone&includeMergeAudits=false&propertyMode=value_only`

**Comment by zxdong262** [comment]
The leatest release fixed it
