### ISSUE TITLE
Task: Call

### ISSUE THREAD

**Issue by JanBilton** [ringcentral/hubspot-embeddable-ringcentral-phone#199]
Hi - I created a task to call a contact, went to the task queue and selected start.  When the task is displayed, the Hubspot softphone pops up (rather than your Chrome app version) and the telephone number isn't ready to dial.  Instead, I have to click the native HS call button.

**Comment by zxdong262** [comment]
Not support that yet, you may try the integration in HubSpot app market: https://www.ringcentral.com/apps/call-with-ringcentral-for-hubspot
