### ISSUE TITLE
RingCentral Hubspot Internal Server Issue 

### ISSUE THREAD

**Issue by jin-fhg** [ringcentral/hubspot-embeddable-ringcentral-phone#200]
Hello @zxdong262 

We have a RingCentral Customer having issues with the Hubspot Integration where it shows Internal Server Error when logging in to the RC widget. 
Here is the video of the issue: https://drive.google.com/file/d/1UUQY7ON7Dj-MmHLSLhe0YiD8-8ESknKk/view?usp=sharing

I tried re-enabling the integration but it did not work. 
Here is the Console file
[app.hubspot.com-1592834313211.log](https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/files/4813852/app.hubspot.com-1592834313211.log)

**Comment by zxdong262** [comment]
Seems youare talking about another app: https://github.com/ringcentral/ringcentral-integration-for-hubspot
Please try select HubSpot as call provider and reselect RingCentral as call provider.

**Comment by jin-fhg** [comment]
Hello @zxdong262 , 

Where do we select Hubspot as the Call Provider and reselect RingCentral? Can you show me a screenshot?

**Comment by jin-fhg** [comment]
Thanks @zxdong262. That works!
