### ISSUE TITLE
Log SMS

### ISSUE THREAD

**Issue by cpopovec** [ringcentral/hubspot-embeddable-ringcentral-phone#201]
For the RingCentral chrome extension, I am seeing that an sms message is being logged as a "call" 

This must be a mistake.  can this be adjusted so that an sms message sent from RingCentral is logged as an "sms" and not as a "call"

**Comment by zxdong262** [comment]
HubSpot have call or note type, but no SMS type, which one do you prefer? call or note?

**Comment by cpopovec** [comment]
Thanks for the reply.

Neither works for us because it does not make sense for an sms to be logged as a call or a note because it is an SMS.

Why can’t it be logged as an “sms"

**Comment by zxdong262** [comment]
Because HubSpot API do not have such type.

**Comment by cpopovec** [comment]
Wouldn't it make sense that RingCentral would create this customization for their integration with HubSpot?  seeing as to how their services provide "calling" and "sms" services?

**Comment by zxdong262** [comment]
Sorry  I do not how to create SMS type without HubSpot's support

**Comment by cpopovec** [comment]
If I have a developer on my team create a custom type in hubspot called “sms” can we have the RingCentral chrome extension log sms messages to it in HubSpot?

**Comment by zxdong262** [comment]
@cpopovec I am not sure, let me ask HubSpot developer about this, I will get back to you.

**Comment by cpopovec** [comment]
Ok, Thank you.
