### ISSUE TITLE
Hubspot Permissions

### ISSUE THREAD

**Issue by raphaelvarieras** [ringcentral/hubspot-embeddable-ringcentral-phone#202]
Does a user need to be a Hubspot Super Admin in order to install the extension. Since I am I could install without difficulty but my users who are not Super Admins were told they needed to be.

**Comment by zxdong262** [comment]
https://github.com/ringcentral/ringcentral-integration-for-hubspot/blob/master/features-compare.md

Seems you mixed up two apps, the chrome extension, no need to be super admin to install, but the intgration, need to be a hubSpot super admin to install it, but normal user could use it.

**Comment by raphaelvarieras** [comment]
That makes sense, thank you.
