### ISSUE TITLE
Timeline API - Logging SMS

### ISSUE THREAD

**Issue by cpopovec** [ringcentral/hubspot-embeddable-ringcentral-phone#204]
Good Morning,

My team is creating a custom sms logging using the timeline APIs for HubSpot.  we would like all of the SMS messages sent from our employees using the RingCentral chrome extension to hit our custom logging instead of being logged using the engagement type of "call" or "notes"

Can we have some support in doing this?

**Comment by cpopovec** [comment]
can i please get a response for this request?  how can we turn off the the logging for the chrome extension so that we can route all of our logs for sms messages to hit our own custom timeline event instead of being logged as an engagement

**Comment by zxdong262** [comment]
@cpopovec Sure, I will add a switch in setting

**Comment by zxdong262** [comment]
Oh,  wait, there are already switchs in settings to turn off the autolog for sms and calls

**Comment by cpopovec** [comment]
Thank you but is there a way we can access the code so that we can remove it completely for our users?

I don’t even want the autologous toggle to exist for them.

Thanks,
Chris

**Comment by zxdong262** [comment]
@cpopovec I see, let me check, this may some days.

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v3.0.0

@cpopovec Done, now with a no call log distribution

**Comment by cpopovec** [comment]
I still want to auto log the calls, I just don’t want the messages to be auto-logged.

Does this make sense?

**Comment by zxdong262** [comment]
No problem @cpopovec I will update the release

**Comment by zxdong262** [comment]
@cpopovec https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v3.0.0
Now with a no-sms-log dist

**Comment by cpopovec** [comment]
Thanks you.

Please work with my colleague Krishna.

Thanks,
Chris

**Comment by kkannaji** [comment]
Hi Zhao,

We are trying to log all the sms activities (Hubspot workflow automation, Ringcentral chrome extension and Ringcentral mobile app) using timeline apis into Hubspot, figured out a way to log automation and extension.

I am using message store api to see all the Inbound and Outbound messages.(https://platform.devtest.ringcentral.com/restapi/v1.0/account/accountId/extension/extensionId/message-store )

Coming to mobile app, I am using production credentials to login and hence i am unable to see the data in the api. Is there a way to login using sandbox credentials for the app, so I can see the data in the message store api and can log into hubspot.

Please let me know, if you can provide me the sandbox credentials for the mobile app.

Thanks,
krishna

**Comment by zxdong262** [comment]
@kkannaji Sandbox credentials only works for sandbox account, you need production credentials to access production data

**Comment by kkannaji** [comment]
I have production credentials for mobile app, can you provide me sandbox credentials for the mobile app, so that when I send the message, can see them using message store api

**Comment by jrheidkamp** [comment]
Hi.  I am using the latest release 4.0.0 and the integration to HubSpot.  Seems outbound SMS is being logged for me, however, inbound SMS is not.  Any ideas?

**Comment by zxdong262** [comment]
> Hi. I am using the latest release 4.0.0 and the integration to HubSpot. Seems outbound SMS is being logged for me, however, inbound SMS is not. Any ideas?

Fixed in latest release, you can try it.

**Comment by jrheidkamp** [comment]
Thank you for fixing the log to notes!  

Next question - we want to use RC Meetings with the webinar add on.     Currently, we use Zoom and it tracks:  

Registration: Displays a list of registrants and their registration details.
Attendee: Displays details about each attendee.
Performance: Displays engagement statistics on registration, attendance and feedback.
Q&A: Displays questions and answers from the webinar.
Polling: Displays each attendee poll result.

This is listed on RingCentral's support page, however,  it does not work.    https://support.ringcentral.com/s/article/9364?language=en_US

Can this be implemented?   

Thank you!
