### ISSUE TITLE
Logged calls appear as notes

### ISSUE THREAD

**Issue by grimeshine** [ringcentral/hubspot-embeddable-ringcentral-phone#208]
Why is it that after a call instead of opening up the "log window" it opens up the "notes window" in hubspot. It makes the feature pretty useless, how can I make this automatically open my call log window instead?

**Comment by zxdong262** [comment]
Released new version that do not open the note window anymore when you click the log link.

**Comment by grimeshine** [comment]
It is still auto-opening the note window when customers call. Can you make it auto open the call log window please

**Comment by zxdong262** [comment]
Oh I see @grimeshine next release will fix

**Comment by zxdong262** [comment]
@grimeshine Please try the latest release, thank you for the feedback!

**Comment by zxdong262** [comment]
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v3.3.0
