### ISSUE TITLE
Customized chrome extension to login using sandbox credentials

### ISSUE THREAD

**Issue by kkannaji** [ringcentral/hubspot-embeddable-ringcentral-phone#209]
Hi Zhao,

I added chrome extension to my hubspot account. However, it appears to be trying to connect to production. How do I get it to connect to my sandbox account?

How to develop a customized chrome extension inorder to login with sandbox, so that I can even see all the sent/received messages in message store api.

Thanks,
Krishna

**Comment by zxdong262** [comment]
<img width="857" alt="Screen Shot 2020-07-29 at 7 19 37 AM" src="https://user-images.githubusercontent.com/1641949/88739230-a7328300-d16c-11ea-8f8c-89fba4319f49.png">

Sorry for the late response.

Check this, need to input `toggleEnv()` in console to open app setting, then you can set it there, and remember to save
