### ISSUE TITLE
Ringcentral Video not the default

### ISSUE THREAD

**Issue by JanBilton** [ringcentral/hubspot-embeddable-ringcentral-phone#210]
Hi - When creating a video meeting in hubspot, the Ringcentral meeting text, rather than Ringcentral video, is copied into the invite.

**Comment by zxdong262** [comment]
Since the RingCentral Video is new, so only new customer will enable RingCentral Video by default.
You can change it to RingCentral Video from RingCentral desktop app's setting -> video page.
