### ISSUE TITLE
Missing call-sms-video buttons for Contacts

### ISSUE THREAD

**Issue by markscacco** [ringcentral/hubspot-embeddable-ringcentral-phone#211]
The toolbar with the call-sms-video buttons that is supposed to display under the contact's name is not showing on Contacts page:
![image](https://user-images.githubusercontent.com/58789961/88728051-77e12f00-d0f6-11ea-9d18-c0e84c3b5583.png)

However, it does show on Company pages:
![image](https://user-images.githubusercontent.com/58789961/88727984-584a0680-d0f6-11ea-9e59-47e214030087.png)

**Comment by zxdong262** [comment]
Is the url like `/contacts/xxxxxx/contact/xxxxx/`? Only support contact page and company page, not deal page

**Comment by markscacco** [comment]
yes, like this:
https://app.hubspot.com/contacts/478xxxx/contact/6xxxx

**Comment by zxdong262** [comment]
Can you try this: in console input `document.querySelector('[data-unit-test="highlightSubtitle"]')` and press enter to see if what is the result?
<img width="1428" alt="Screen Shot 2020-07-29 at 7 56 15 AM" src="https://user-images.githubusercontent.com/1641949/88740982-101bfa00-d171-11ea-8428-a4ce287a303b.png">

**Comment by markscacco** [comment]
![image](https://user-images.githubusercontent.com/58789961/88741257-cc8ba680-d104-11ea-8d02-4926c3e1a88b.png)

**Comment by zxdong262** [comment]
Can we have a meeting to check it?
@markscacco

**Comment by markscacco** [comment]
yes im available now

**Comment by zxdong262** [comment]
Great, please send an email to drake.zhao@ringcentral.com, I will reply with meeting link. @markscacco

**Comment by markscacco** [comment]
ok i see now that the Contact (or company) must have a phone number associated with them. Thank you for your help!

**Comment by markscacco** [comment]
Thank you very much for your prompt responses.
I suggest that the buttons should display even when there is not a phone number associated with the contact or company. The buttons could be faded and inoperable when there is no phone number. A consistent user-interface would reduce potential user confusion. Thanks for the great work on this.
Mark

**Comment by zxdong262** [comment]
@markscacco You are right!
