### ISSUE TITLE
Unable to dial numbers with extensions

### ISSUE THREAD

**Issue by markscacco** [ringcentral/hubspot-embeddable-ringcentral-phone#212]
If the contact's phone number has an extension, the app is unable to dial the number.
For example, 555.555.5555 x 9 (nor any similar notation, such as * 9 or ext 9) cannot be dialed and returns the message "Please enter a valid phone number."

What's interesting is that the RingCentral desktop app can interpret extensions of this format and dial them. It would be a great addition to be able to have it dial numbers with extensions.

Thanks,
Mark

**Comment by embbnux** [comment]
Hi Mark,
Can you show screenshot of how you dial the contact. Do you dial from contact's page, or just typing?
It should work when you dial number as `9999990000*101` or `101` for internal call.

**Comment by markscacco** [comment]
@embbnux This issue is specifically related to the ringcentral app for hubspot. To dial the contact, you click the phone icon as shown below:

![image](https://user-images.githubusercontent.com/58789961/88997690-daccf480-d2b5-11ea-8cd1-291e39572b39.png)

**Comment by markscacco** [comment]
@zxdong262 Can you comment on this issue?

**Comment by zxdong262** [comment]
@markscacco I will check this, thank you for the feedback.

**Comment by markscacco** [comment]
@zxdong262 thanks!

**Comment by zxdong262** [comment]
@markscacco Released new version with fix, you may try it.

**Comment by markscacco** [comment]
Nice! It works! Thank you
