### ISSUE TITLE
Action button are missing when the Task queue is active

### ISSUE THREAD

**Issue by markscacco** [ringcentral/hubspot-embeddable-ringcentral-phone#213]
when the Task queue is active, the ringcentral plugin action icons (call, sms, etc) are not visible or active:

![image](https://user-images.githubusercontent.com/58789961/89068111-363ec700-d336-11ea-8e36-e80f97ed96d5.png)

As soon as I close the queue (by clicking the X in the upper right, the action button become visible

**Comment by zxdong262** [comment]
We do not support tasks, please try ringcentral labs from HubSpot app market
