### ISSUE TITLE
Manual call logging text editor issues

### ISSUE THREAD

**Issue by markscacco** [ringcentral/hubspot-embeddable-ringcentral-phone#216]
when manually logging a call, carriage returns (Enter to move to new line) are not transferring from the notes editor in the RC app to the note recorded in Hubspot. For example, I might type the following in RC when manually logging  call notes:

![image](https://user-images.githubusercontent.com/58789961/89210687-2e756180-d586-11ea-82b2-b7df4a0a9731.png)

However, once submitted to hubspot, it looks like this:

![image](https://user-images.githubusercontent.com/58789961/89210785-5bc20f80-d586-11ea-9c21-f3e9f802ce1f.png)

**Comment by zxdong262** [comment]
@markscacco Thank you for the feedback
https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v3.5.1 New release with support
