### ISSUE TITLE
Manually Logging calls associated with a Company Does Not Work

### ISSUE THREAD

**Issue by markscacco** [ringcentral/hubspot-embeddable-ringcentral-phone#217]
when I review the history of calls and use the tool to manually log a call to a phone number associated with a Company (and not a Contact) the call is logged to my own contact record in hubspot and not with the company associated with the phone number dialed.

**Comment by zxdong262** [comment]
The app will log any contact/company with callee or caller number, so if you have the same number as the company, it will log to your call log too.

**Comment by markscacco** [comment]
Thank you. It's not logging with the company or the contact, it's logging
under MY contact record.

**Comment by zxdong262** [comment]
@markscacco Your contact's phone number is not the caller or callee? In that case can we have a meeting to check it?

**Comment by markscacco** [comment]
I will check when I return to the office and report back.

**Comment by markscacco** [comment]
ok i've investigated further. I am struggling to determine what causes the problem.
I use the RC plugin to call a contact.
The contact has a phone number associated with it
The call connects and the app logs it in its history
However, intermittently, the call is not logged in hubspot.

As I mentioned at the start of this thread, if I next attempt to manually log the call via the RC plugin, the call log is associated with MY contact record, and not with the client contact or company record.

Possible causes:
1. the contact and the company have the same phone number
2. the contact has the same company number with an extension
3. ??

**Comment by markscacco** [comment]
@zxdong262 continuing to have issues with calls not logging. The plugin no longer appears to be working properly. When I place a call to a Company, the call is not  automatically logged with the company. If I manually log the call (via the History tab in the plugin) the call is logged to MY contact and company record. However,  the logged call does not show when viewing all ACTIVITY in my feed. Only when I choose CALLS does it show. I then have to manually reassign the contact and company with which the call is supposed to be associated (the client contact and company).

**Comment by markscacco** [comment]
@zxdong262 Update: Neither calls to Contact or Company are logging automatically

**Comment by zxdong262** [comment]
Have you follow the video instruction to enable auto log and synced all contacts data?
@markscacco 
https://youtu.be/ajbipkPd_4Q

**Comment by markscacco** [comment]
Yes

**Comment by zxdong262** [comment]
@markscacco Can we have a meeting to check it?

If you can, please send your availble time/timezone to drake.zhao@ringcentral.com, I will send you the meeting link.
