### ISSUE TITLE
Auto Log Call and Auto Log SMS toggle switches missing

### ISSUE THREAD

**Issue by metalxoa** [ringcentral/hubspot-embeddable-ringcentral-phone#219]
Hello. Thank you so much for putting this together, very impressive and useful extension. 

I have noticed in other posts that people have two toggle switches that I do not seem to have. I've included a screen shot below. 

![Auto Log](https://user-images.githubusercontent.com/69307587/89531315-083a0680-d7be-11ea-9e52-fb719d2a11df.png)

I'm sure there is a simple setting or solution that I'm missing. Could you point me in the right direction? 

Thanks

**Comment by zxdong262** [comment]
You should download the first one, not the `no-auto-call-log` one
