### ISSUE TITLE
Manually logging calls returns "call log sync to hubspot failed" error

### ISSUE THREAD

**Issue by markscacco** [ringcentral/hubspot-embeddable-ringcentral-phone#220]
After I attempt to manually log a call I get the following error. Im using version 3.5.4

![image](https://user-images.githubusercontent.com/58789961/89942543-60b83c00-dbe2-11ea-891e-0358200537b3.png)

**Comment by zxdong262** [comment]
Can you try resync all contacts and do it again?

**Comment by zxdong262** [comment]
Is the contact newly added before last time you sync contacts data?

**Comment by markscacco** [comment]
No, it's a contact that's been in the database for a while

Thanks,
Mark

**Comment by zxdong262** [comment]
@markscacco Is the contact showing a name or just number in call history panel?

**Comment by markscacco** [comment]
Full name and number

**Comment by zxdong262** [comment]
@markscacco Can we have a meeting to check it? If you can, please send your available time/time zone to drake.zhao@ringcentral.com, (please exclude 0:00 AM - 7:00 AM UTC+8 timzone), I will send you the meeting link.

**Comment by markscacco** [comment]
Hi Drake,

Please use this link to pick a time that works for you: Schedule a Meeting
with Mark
<https://t.sidekickopen81.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FfhMynW4X9X2g7d-mXxW56dSNP5YV86-102?te=W3R5hFj4cm2zwW3_SMKM3T1k87W1JzCRv4cNDSbW1JxwY51LBbZjW3Xtnm93z8myJw1L6_5c4dz2&si=7000000001690347&pi=4df8315b-fb13-4769-ddc9-b840ecc0a35a>

Thank you,

Mark Scacco, PE
*AEC Industry Consultant*
*Scacco, LLC*
*Certified: DBE | WBE | OSHA 30*
*t*: 330.732.5489 | *d*: 630.506.5564 | *m*: 630.816.6605
LinkedIn
<https://t.sidekickopen81.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-FfhMynW4X9X2g7d-mXxW56dSNP5YV86-102?te=W3R5hFj26QkHmW4mKDt23T1kvSW3H6wS-3Fbt5SW3T1ddy3zgDn7w3F4DCB48V2&si=7000000001690347&pi=4df8315b-fb13-4769-ddc9-b840ecc0a35a>
