### ISSUE TITLE
Syncing contacts never completes

### ISSUE THREAD

**Issue by markscacco** [ringcentral/hubspot-embeddable-ringcentral-phone#222]
When syncing all my contacts, it never completes. I've kept the page open for more than a day and it never finishing syncing. I have successfully synced in the past and have not made significant changes to our contacts. I think there is an issue with the latest release

**Comment by zxdong262** [comment]
Can we have a meeting to check it?  I can not reproduce this.

**Comment by markscacco** [comment]
Yes, please email me to arrange day/time
