### ISSUE TITLE
No RC Meeting Link when on a company page

### ISSUE THREAD

**Issue by jrheidkamp** [ringcentral/hubspot-embeddable-ringcentral-phone#223]
When on a company page, and clicking on meet or meeting, the RingCentral link is not populating.  See screenshots of contact (works) vs Company (does not work).  
![screenshot-app hubspot com-2020 09 11-23_53_21](https://user-images.githubusercontent.com/70994618/92987699-86a75980-f48a-11ea-86ac-5f315cd6bc57.png)
![screenshot-app hubspot com-2020 09 11-23_54_15](https://user-images.githubusercontent.com/70994618/92987700-873ff000-f48a-11ea-9073-d73c589e32da.png)

**Comment by zxdong262** [comment]
Done: https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/releases/tag/v4.1.2

**Comment by jrheidkamp** [comment]
When on a contact page, and you click on Meetings, It pops up Meeting in background and auto saves meeting info so you can automatically email the contact.   Would like to have the same on the company page:

On a Contact Screen:

![screenshot-app hubspot com-2020 09 14-08_12_05](https://user-images.githubusercontent.com/70994618/93090563-8bbf0100-f662-11ea-8756-c2eb01cc58c5.png)

Once you click on Meeting in RC Extension:

![screenshot-app hubspot com-2020 09 14-08_17_53](https://user-images.githubusercontent.com/70994618/93090760-dccef500-f662-11ea-99fd-212931b59697.png)

![screenshot-app hubspot com-2020 09 14-08_19_01](https://user-images.githubusercontent.com/70994618/93090908-0b4cd000-f663-11ea-8219-546de80ee812.png)


However, under the company you get this:

![screenshot-app hubspot com-2020 09 14-08_20_07](https://user-images.githubusercontent.com/70994618/93090980-23245400-f663-11ea-8239-afc836a2b79e.png)

So it is not copying the meeting info over to a meeting in HS.

**Comment by zxdong262** [comment]
@jrheidkamp I see, I missed something,  I will fix it tomorrow.
