### ISSUE TITLE
When on a contact page, and you click on Meetings, It pops up Meeting in background and auto saves meeting info so you can automatically email the contact.   Would like to have the same on the company page:

### ISSUE THREAD

**Issue by jrheidkamp** [ringcentral/hubspot-embeddable-ringcentral-phone#225]
When on a contact page, and you click on Meetings, It pops up Meeting in background and auto saves meeting info so you can automatically email the contact.   Would like to have the same on the company page:

On a Contact Screen:

![screenshot-app hubspot com-2020 09 14-08_12_05](https://user-images.githubusercontent.com/70994618/93090563-8bbf0100-f662-11ea-8756-c2eb01cc58c5.png)

Once you click on Meeting in RC Extension:

![screenshot-app hubspot com-2020 09 14-08_17_53](https://user-images.githubusercontent.com/70994618/93090760-dccef500-f662-11ea-99fd-212931b59697.png)

![screenshot-app hubspot com-2020 09 14-08_19_01](https://user-images.githubusercontent.com/70994618/93090908-0b4cd000-f663-11ea-8219-546de80ee812.png)

However, under the company you get this:

![screenshot-app hubspot com-2020 09 14-08_20_07](https://user-images.githubusercontent.com/70994618/93090980-23245400-f663-11ea-8239-afc836a2b79e.png)

So it is not copying the meeting info over to a meeting in HS.

_Originally posted by @jrheidkamp in https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/223#issuecomment-692048112_

**Comment by zxdong262** [comment]
We can not support company
