### ISSUE TITLE
SMS/MMS drop down does not differentiate Phone Number Type

### ISSUE THREAD

**Issue by jrheidkamp** [ringcentral/hubspot-embeddable-ringcentral-phone#226]
![image](https://user-images.githubusercontent.com/70994618/93103983-e95b4980-f672-11ea-8bd1-ab1e5121c5ad.png)

Possible that this can decipher Phone Type?  Main Business Number, Direct Line, Mobile, Fax, etc?

**Comment by zxdong262** [comment]
Right!

**Comment by zxdong262** [comment]
Fixed in latest release, thank you for the feedback
