### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jrheidkamp** [ringcentral/hubspot-embeddable-ringcentral-phone#227]
Logging a lot of errors.  Is this normal?

/ RingCentral Embeddable Voice for HubSpot / Errors

RingCentral Embeddable Voice for HubSpot

Issues100 found

Clear all
AccountInfo is deprecated, please evaluate and transition to use AccountInfoV2

ActiveCalls module is deprecated, please use Presence module with detailed mode

RcModule requires AlertUI._onStateChange to be implemented.

Mon Sep 14 2020 15:09:23 GMT-0500 (Central Daylight Time) | sip.transport | Tried to assert 1 but is currently 0

Mon Sep 14 2020 15:09:23 GMT-0500 (Central Daylight Time) | sip.transport | Status transition failed - result: no-op - reason: either gave an nonexistent status or attempted illegal transition

Mon Sep 14 2020 15:09:23 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

fetchData error: TypeError: Failed to fetch

Mon Sep 14 2020 15:10:21 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

Mon Sep 14 2020 15:10:48 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

appKey is deprecated, please change to clientId. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md

AccountInfo is deprecated, please evaluate and transition to use AccountInfoV2

ActiveCalls module is deprecated, please use Presence module with detailed mode

RcModule requires AlertUI._onStateChange to be implemented.

appKey is deprecated, please change to clientId. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md

AccountInfo is deprecated, please evaluate and transition to use AccountInfoV2

ActiveCalls module is deprecated, please use Presence module with detailed mode

RcModule requires AlertUI._onStateChange to be implemented.

Mon Sep 14 2020 15:10:56 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

appKey is deprecated, please change to clientId. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md

AccountInfo is deprecated, please evaluate and transition to use AccountInfoV2

ActiveCalls module is deprecated, please use Presence module with detailed mode

RcModule requires AlertUI._onStateChange to be implemented.

Mon Sep 14 2020 15:13:13 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

Mon Sep 14 2020 15:13:26 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

appKey is deprecated, please change to clientId. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md

AccountInfo is deprecated, please evaluate and transition to use AccountInfoV2

ActiveCalls module is deprecated, please use Presence module with detailed mode

RcModule requires AlertUI._onStateChange to be implemented.

Mon Sep 14 2020 15:13:30 GMT-0500 (Central Daylight Time) | sip.ua | UA Registration Failed

Webphone Register Error: [object Object] Rejected

appKey is deprecated, please change to clientId. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md

AccountInfo is deprecated, please evaluate and transition to use AccountInfoV2

ActiveCalls module is deprecated, please use Presence module with detailed mode

RcModule requires AlertUI._onStateChange to be implemented.

Mon Sep 14 2020 15:13:43 GMT-0500 (Central Daylight Time) | sip.ua | UA Registration Failed

Error: unregistered timeout

Mon Sep 14 2020 15:14:15 GMT-0500 (Central Daylight Time) | sip.ua | UA Registration Failed

Webphone Register Error: [object Object] Rejected

Error: unregistered timeout

Mon Sep 14 2020 15:14:48 GMT-0500 (Central Daylight Time) | sip.ua | UA Registration Failed

Webphone Register Error: [object Object] Rejected

Mon Sep 14 2020 15:16:48 GMT-0500 (Central Daylight Time) | sip.transport | WebSocket closed without SIP.js requesting it

Mon Sep 14 2020 15:16:48 GMT-0500 (Central Daylight Time) | sip.transport | trying to reconnect to WebSocket wss://sip132-141.ringcentral.com:8083 (reconnection attempt 1)

Mon Sep 14 2020 15:16:48 GMT-0500 (Central Daylight Time) | sip.transport | next reconnection attempt in:3 seconds.

Mon Sep 14 2020 15:16:49 GMT-0500 (Central Daylight Time) | sip.transport | Tried to assert 1 but is currently 3

Mon Sep 14 2020 15:16:49 GMT-0500 (Central Daylight Time) | sip.transport | Status transition failed - result: no-op - reason: either gave an nonexistent status or attempted illegal transition

Webphone Register Error: undefined Connection Error

Mon Sep 14 2020 15:16:51 GMT-0500 (Central Daylight Time) | sip.ua | UA Registration Failed

Error: unregistered timeout

Mon Sep 14 2020 15:16:52 GMT-0500 (Central Daylight Time) | sip.ua | UA Registration Failed

Mon Sep 14 2020 15:18:52 GMT-0500 (Central Daylight Time) | sip.transport | WebSocket closed without SIP.js requesting it

Mon Sep 14 2020 15:18:52 GMT-0500 (Central Daylight Time) | sip.transport | trying to reconnect to WebSocket wss://sip132-141.ringcentral.com:8083 (reconnection attempt 1)

Mon Sep 14 2020 15:18:52 GMT-0500 (Central Daylight Time) | sip.transport | next reconnection attempt in:2 seconds.

Mon Sep 14 2020 15:18:55 GMT-0500 (Central Daylight Time) | sip.ua | UA Registration Failed

Webphone Register Error: [object Object] Rejected

Mon Sep 14 2020 15:20:55 GMT-0500 (Central Daylight Time) | sip.transport | WebSocket closed without SIP.js requesting it

Mon Sep 14 2020 15:20:55 GMT-0500 (Central Daylight Time) | sip.transport | trying to reconnect to WebSocket wss://sip132-141.ringcentral.com:8083 (reconnection attempt 1)

Mon Sep 14 2020 15:20:55 GMT-0500 (Central Daylight Time) | sip.transport | next reconnection attempt in:5 seconds.

Mon Sep 14 2020 15:22:25 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

Mon Sep 14 2020 15:23:31 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

Mon Sep 14 2020 15:23:39 GMT-0500 (Central Daylight Time) | sip.ua | UA Registration Failed

Mon Sep 14 2020 15:23:51 GMT-0500 (Central Daylight Time) | sip.ua | UA Registration Failed

Mon Sep 14 2020 15:24:23 GMT-0500 (Central Daylight Time) | sip.ua | UA Registration Failed

Error: unregistered timeout

Mon Sep 14 2020 15:24:28 GMT-0500 (Central Daylight Time) | sip.ua | UA Registration Failed

Webphone Register Error: [object Object] Rejected

appKey is deprecated, please change to clientId. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md

AccountInfo is deprecated, please evaluate and transition to use AccountInfoV2

ActiveCalls module is deprecated, please use Presence module with detailed mode

RcModule requires AlertUI._onStateChange to be implemented.

Mon Sep 14 2020 15:26:39 GMT-0500 (Central Daylight Time) | sip.ua | UA Registration Failed

Error: unregistered timeout

Mon Sep 14 2020 15:26:51 GMT-0500 (Central Daylight Time) | sip.ua | UA Registration Failed

Webphone Register Error: [object Object] Rejected

Mon Sep 14 2020 15:27:57 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

appKey is deprecated, please change to clientId. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md

AccountInfo is deprecated, please evaluate and transition to use AccountInfoV2

ActiveCalls module is deprecated, please use Presence module with detailed mode

RcModule requires AlertUI._onStateChange to be implemented.

Mon Sep 14 2020 16:09:25 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

appKey is deprecated, please change to clientId. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md

AccountInfo is deprecated, please evaluate and transition to use AccountInfoV2

ActiveCalls module is deprecated, please use Presence module with detailed mode

RcModule requires AlertUI._onStateChange to be implemented.

Mon Sep 14 2020 16:11:15 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

Mon Sep 14 2020 16:21:16 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

appKey is deprecated, please change to clientId. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md

AccountInfo is deprecated, please evaluate and transition to use AccountInfoV2

ActiveCalls module is deprecated, please use Presence module with detailed mode

RcModule requires AlertUI._onStateChange to be implemented.

Mon Sep 14 2020 16:21:35 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

appKey is deprecated, please change to clientId. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md

AccountInfo is deprecated, please evaluate and transition to use AccountInfoV2

ActiveCalls module is deprecated, please use Presence module with detailed mode

RcModule requires AlertUI._onStateChange to be implemented.

Mon Sep 14 2020 16:21:44 GMT-0500 (Central Daylight Time) | sip.ua | UA already closed

appKey is deprecated, please change to clientId. https://github.com/ringcentral/ringcentral-embeddable/blob/master/docs/config-client-id-and-secret.md

AccountInfo is deprecated, please evaluate and transition to use AccountInfoV2

ActiveCalls module is deprecated, please use Presence module with detailed mode

RcModule requires AlertUI._onStateChange to be implemented.

**Comment by zxdong262** [comment]
You can ignore these as long as functions works as expected.
