### ISSUE TITLE
Auto sync not for new contact?

### ISSUE THREAD

**Issue by TobiasLicker** [ringcentral/hubspot-embeddable-ringcentral-phone#229]
If I understand correctly, the call log would auto sync only if the contacts are already in Hubspot with name and email, correct?

 If a potential new client calls, it is not synced automatically, the agent would have to add name and email to the phone number in order to add it to Hubspot contacts, correct?

Would it be possible to auto sync all incoming calls first to Deals for example so that it's not up to the agent's work ethic to record a call as potential new client or not?

**Comment by zxdong262** [comment]
The 7.x version do support auto sync contacts, no need to do anything.
