### ISSUE TITLE
Call logging against all the contacts in the same company

### ISSUE THREAD

**Issue by Naghiyev1** [ringcentral/hubspot-embeddable-ringcentral-phone#231]
It is important for our sales team to find a viable calling solution that works with Hubspot. We have been using and selling Avaya/RingCentral for a number of years and have found a big issue with this integration.

When you call one person on the company record it automatically logs call against all the contacts in the same company. It creates problems for reporting as the data is not accurate any more. This problem occurs if you don't have DDI registered for the contacts and using the main company number on your records. 

Would appreciate any help.

**Comment by zxdong262** [comment]
@Naghiyev1 Do these contacts have same number, if so it is expected, call log will sync to all contacts with caller or callee's number, so if you want to avoid some contacts to be logged, make sure the conatcts do not have the duplicate number.

**Comment by Naghiyev1** [comment]
@zxdong262 Yes, this is the exact reason why it's happening but unfortunately, it's not a suitable solution for us as we want to keep the numbers as they are. I wonder if it would be possible to add 'if then' statement to the component to avoid registering duplicates.

**Comment by eringallagher1411** [comment]
I'm having the same issue.  I have 8 people in a queue for incoming calls.  They all have separate phones, but take calls coming in to the main line.  When it logs, it shows multiple people logging calls.

**Comment by zxdong262** [comment]
The latest release would let user choose which contacts to log the call.
