### ISSUE TITLE
Auto sync not syncing

### ISSUE THREAD

**Issue by JanBilton** [ringcentral/hubspot-embeddable-ringcentral-phone#232]
Hi - I have auto-sync enabled, but after I've made a call, unless I stay on the contact page it won't sync.  In addition, if I stay on the contact page, after about 20 seconds the sync prompt appears.  If I click sync on that, it works, or if I leave it to count down it also logs the call.  Doesn't auto-sync log the call immediately?

**Comment by zxdong262** [comment]
@JanBilton Can not log immediately becasue server have to process it, it may take some time, when there is recording, it may take more time. Also the countdown phase provide a chance to select result

**Comment by JanBilton** [comment]
Thanks.  However there are instances, although not every time, where the call doesn't log at all.

**Comment by KDLN** [comment]
Having the same issue, the sync does not even pop up for me 90% of the time. Then it tries to sync and shows up sometimes a day or two later. Even refreshing contacts and running a test in the am does not work.

**Comment by zxdong262** [comment]
@KDLN @JanBilton Make sure new contacts are synced to widgets.

**Comment by zxdong262** [comment]
The latest release would work
