### ISSUE TITLE
Req/Ask SMS Logged as Call / type 

### ISSUE THREAD

**Issue by KDLN** [ringcentral/hubspot-embeddable-ringcentral-phone#233]
Is there a way to log texts as SMS vs Note? Our marketing uses that in reports and helps decide and drive some marketing based on contacts made or received, and SMS as a note does not count and let them see it reported correctly. 

![image](https://user-images.githubusercontent.com/17499497/97870435-f98dbd80-1ce0-11eb-9d06-1b78471d1633.png)

**Comment by zxdong262** [comment]
@KDLN Currently can not support it, because SMS is not a built-in type

**Comment by KDLN** [comment]
> @KDLN Currently can not support it, because SMS is not a built-in type

Ah sorry did not realize that was custom. Is there a way to log it in there with a numbered index that lines up with custom call types?

**Comment by zxdong262** [comment]
@KDLN Maybe later, planning a major update to add a setting panel, we could add a select for user to choose custom type.

**Comment by KDLN** [comment]
> @KDLN Maybe later, planning a major update to add a setting panel, we could add a select for user to choose custom type.

Well if you need help testing that feature would love to help there. Thanks for the reply.
