### ISSUE TITLE
No audio output on calls

### ISSUE THREAD

**Issue by dylyman** [ringcentral/hubspot-embeddable-ringcentral-phone#235]
We recently installed the RC extension in our HubSpot instance and users have been reporting intermittent issues with receiving call audio. The other end of the call will be speaking but the user cannot hear anything. This issue doesn't seem to be effecting every call but when it happens the audio is 100% missing for the entire call.

The browser extension does not have the same issues, only comes up when using the HubSpot embedded one.
 
I've been able to verify that the other end of the call did speak by checking the call recordings and have been able to replicate the issue. Connecting/disconnecting an external headset will sometimes fix the issue but it will still come back.

**Comment by dylyman** [comment]
Have also confirmed with users and my in my own testing that the system audio output was set to system speaker/headset as expected.

**Comment by zxdong262** [comment]
@dylyman Issue do exist, most likely related to backend service, not related to integration, need time to confirm.

**Comment by embbnux** [comment]
@dylyman Can you share your area. It may be network issue in some area.

**Comment by dylyman** [comment]
Sure, team is generally located in Toronto (Canada) area. We're all remote though so network conditions vary. If it helps I've included my results from RC's [QoS test](https://www.ringcentral.ca/support/qos.html), as of this morning.

<img width="500" alt="20201126 RTT" src="https://user-images.githubusercontent.com/74986362/100374691-a60a4900-2fda-11eb-9e42-30c02957d3c1.png">
<img width="250" alt="20201126 Visualware Summary" src="https://user-images.githubusercontent.com/74986362/100374694-a73b7600-2fda-11eb-8180-1b82d16aebc0.png">
<img width="500" alt="20201126 VoIP Download" src="https://user-images.githubusercontent.com/74986362/100374695-a73b7600-2fda-11eb-86e2-69adb8252efb.png">
<img width="500" alt="20201126 VoIP Quality" src="https://user-images.githubusercontent.com/74986362/100374698-a9053980-2fda-11eb-9d25-f52b77121711.png">

**Comment by embbnux** [comment]
> The browser extension does not have the same issues, only comes up when using the HubSpot embedded one.

@zxdong262  Does browser extension and embedded one use same Embeddable version.

If browser extension and embedded one using same version, it should a bug in Chrome's iframe audio.

**Comment by zxdong262** [comment]
@embbnux HubSpot embedded one load from github, so always latest, the latest browser extension use 11.19 version

**Comment by zxdong262** [comment]
@embbnux @dylyman HubSpot embedded one should be same as https://ringcentral.github.io/ringcentral-embeddable/, you can try it, I can not reproduce the issue yet, tried many times.

**Comment by zxdong262** [comment]
@embbnux Also, it is running in a iframe in both situations

**Comment by dylyman** [comment]
Strange, team mate just had the issue crop up again. Exact same problem; other end of the call is speaking and can be heard on the recording but RC user can't hear anything. This was with the HS-embedded dialer. 

If we manage to catch the bug "live" is there anything we can share with you? A debug log or something.

**Comment by zxdong262** [comment]
@dylyman I do not know yet, since I never catch the issue, and could be issue from websocket, so may not catch any issue from log.

**Comment by dylyman** [comment]
OK have two users confirming that they consistently experiencing this issue. Both report it happening intermittently and randomly impacting calls with no changes on their end. Trying various headsets and audio output options doesn't fix it. 

A third user doesn't seem to be having this issue, is there anything worth checking with his setup? Chrome version, OS version, extension version, etc.?

**Comment by zxdong262** [comment]
@dylyman It would be great to see all the env difference, maybe we can find out the key factor.

**Comment by dylyman** [comment]
Here are the user agents:

**With Issues**

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
>Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

**No reported issues so far**
>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36

**Comment by embbnux** [comment]
> Strange, team mate just had the issue crop up again. Exact same problem; other end of the call is speaking and can be heard on the recording but RC user can't hear anything. This was with the HS-embedded dialer.
> 
> If we manage to catch the bug "live" is there anything we can share with you? A debug log or something.

The voice transmission is handled by WebRTC protocol  from Browser. So it is hard to track the log. Can you let users who has this issue happened to test their network when they are facing voice lost.

**Comment by dylyman** [comment]
> > Strange, team mate just had the issue crop up again. Exact same problem; other end of the call is speaking and can be heard on the recording but RC user can't hear anything. This was with the HS-embedded dialer.
> > If we manage to catch the bug "live" is there anything we can share with you? A debug log or something.
> 
> The voice transmission is handled by WebRTC protocol from Browser. So it is hard to track the log. Can you let users who has this issue happened to test their network when they are facing voice lost.

Which test would you recommend?

**Comment by embbnux** [comment]
Qos test from RingCentral is ok https://www.ringcentral.ca/support/qos.html . We should test it when we were facing the issue.
