### ISSUE TITLE
doubling call logs 

### ISSUE THREAD

**Issue by twasheck** [ringcentral/hubspot-embeddable-ringcentral-phone#238]
If there are contacts with different email addresses but the same phone number, when the call logs are synced, it syncs one call for each contact in the entire database that has the same phone number. so one phone call can be logged 4+times.

**Comment by zxdong262** [comment]
It is designed like this @twasheck

**Comment by zxdong262** [comment]
The app would not know which is the one you want to sync the call log, you can mannully call the phone number in any RingCentral device, can you merge the contact with some number into one contact?

**Comment by twasheck** [comment]
I did that once I found out some of the contacts had multiple entries
