### ISSUE TITLE
feat: Only sync contacts in a selected contact list

### ISSUE THREAD

**Issue by tohagan** [ringcentral/hubspot-embeddable-ringcentral-phone#239]
The current code appears to always [fetch ALL contacts](https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/blob/master/src/feat/contacts.js#L256) .  My team has a large number of contact in HubSpot (>100k) most of which are historical so syncing them all is rather pointless.   

Of much greater use would be the ability to sync only the contacts in a selected HubSpot Contact List.  Using the HubSpot [Contact List API](https://legacydocs.hubspot.com/docs/methods/lists/get_list_contacts), you'd also be able to fetch just the fields required which would dramatically reduce the bandwidth consumed.

**Comment by zxdong262** [comment]
@tohagan I will add this to todo list, before it is done, you could do is that finish syncing all once, it would not auto sync all any more, you can choose sync only new/updated contacts next time.

**Comment by tohagan** [comment]
Yes I understand this.  We also have privacy/security concerns about syncing all contacts into every user's browser.

**Comment by tohagan** [comment]
BTW ... Does this app sync contacts into RC servers OR only to local browser?

**Comment by zxdong262** [comment]
@tohagan Only to browser database
