### ISSUE TITLE
Incorrect Number Prefix when Launching RC Phone app

### ISSUE THREAD

**Issue by cedmo8** [ringcentral/hubspot-embeddable-ringcentral-phone#261]
This started around version 1.7.1 where we had to migrate away from the plugin due to this issue, when clicking on a number in UK format e.g. 07123456789 and with both our HubSpot and RingCentral configured for UK +44 the click to dial provided by this plugin presents and passes through to the RC Phone app +1 07123456789 which I understand is the American, this used to me a transient issue affecting about half of all calls but now it is 100% of calls placed through the app add +1 to the start of the number.

**Comment by zxdong262** [comment]
Can you try the latest release?

**Comment by cedmo8** [comment]
Just tried with 7.1.0 and the issue persists.

**Comment by zxdong262** [comment]
@cedmo8 Can we have a meeting to check this, if you can, please send an email to hubspot_support@ringcentral.com, with you available time and timezone, I will send you the meeting link.

**Comment by zxdong262** [comment]
Incase some else encounter this issue, click left bottom RingCentral icon, and click rebuild phone contact index would fix.
