### ISSUE TITLE
Cant login over 

### ISSUE THREAD

**Issue by Ruba85** [ringcentral/hubspot-embeddable-ringcentral-phone#279]
Hello we can't login over RingCentral Embeddable for HubSpot.
![image](https://user-images.githubusercontent.com/58745486/144124509-7fc9db71-8428-47cc-9b6d-82bb5213c874.png)

![image](https://user-images.githubusercontent.com/58745486/144124224-b3f20bf4-e776-453f-ad9b-f620ecc53d61.png)

**Comment by CoCraig** [comment]
Hi @Ruba85 , that issue is with a login redirect selecting the appropriate emergency address location.  Can you open a support ticket at support.ringcentral.com?  The login redirect is handled by another team outside of this HubSpot integration.

**Comment by Ruba85** [comment]
Ok thank you

**Comment by CoCraig** [comment]
Issue may occur again, but should be working right now. Please create a support ticket if this emergency address issue arises again.
