### ISSUE TITLE
Call logs not synced Hubspot

### ISSUE THREAD

**Issue by matt33445** [ringcentral/hubspot-embeddable-ringcentral-phone#291]
I keep getting a Call Logs Not Synced in Hubspot. Clicking sync does nothing but spin. I am signed in to hubspot.  The Chrome extension keep getting the following error:
translation for "{numberof} incomming calls" in "en" is missing

**Comment by CoCraig** [comment]
Hi @matt33445 can you take a screenshot and send it to hubspot_support@ringcentral.com?
