### ISSUE TITLE
Add RingCentral to Hubspot's Meeting Scheduler

### ISSUE THREAD

**Issue by jakethus** [ringcentral/hubspot-embeddable-ringcentral-phone#294]
In Hubspot, it has the booking scheduler feature so that clients can pick a time from my calendar to meet, just like Calendly. In this feature, you can choose a "videoconference" link to set up to go with it. For example, Zoom has this ability and when the client schedules a meeting with us, it also creates a scheduled Zoom meeting that is sent to everyone. I'd like RingCentral to have that power too. We can't let Zoom beat RingCentral, can we? I have attached a picture of when I edit my meeting scheduler, it shows the option to add a videoconference link, and I can choose Zoom
![Screenshot 2022-04-14 132351](https://user-images.githubusercontent.com/103685690/163462523-cd74d240-f1f7-4325-ae0d-f5c41799de0d.jpg)
.

**Comment by CoCraig** [comment]
@jakethus You can also select RingCentral for meetings. Please go here and install this native integration to enable RingCentral.  If you like the integration, or you are looking for something, let us know!
https://www.ringcentral.com/apps/call-with-ringcentral-for-hubspot
![Screen Shot 2022-04-14 at 12 34 11 PM](https://user-images.githubusercontent.com/64171562/163463279-e644f9fd-5033-4d07-90bf-52a0ee683d0a.png)
