### ISSUE TITLE
Release 7.9.15

### ISSUE THREAD

**Issue by sevab** [ringcentral/hubspot-embeddable-ringcentral-phone#296]
Would it be possible to publish 7.9.15 release, as the current 7.9.13 doesn't seem to be working for us in Chrome.
Thanks!

**Comment by zxdong262** [comment]
@sevab Hi, can you send an email to hubspot_support@ringcentral.com, so I can send you a temp download link of 7.9.15, since still in test phase, so may not release it soon.
