### ISSUE TITLE
Can't connect with widget  

### ISSUE THREAD

**Issue by Ruba85** [ringcentral/hubspot-embeddable-ringcentral-phone#302]
When we try to connect we receive {"message": "Internal server error"}
![image](https://user-images.githubusercontent.com/58745486/186695334-ebf56210-6736-4717-b982-0ea20535d77e.png)
Also we cant listen to calls records 
![image](https://user-images.githubusercontent.com/58745486/186695565-89be2162-9a82-4bad-b270-5ce88b097921.png)

**Comment by Ruba85** [comment]
After several attempts, I managed to login
I can make calls but i can to log them to HS
And we have a lot mistakes in console
![image](https://user-images.githubusercontent.com/58745486/186698575-42c5dc95-6bb0-4a02-abc1-3851d2076625.png)

**Comment by embbnux** [comment]
Hi @Ruba85 Can you help to check if you are using this community app or the official extension: https://chrome.google.com/webstore/detail/ringcentral-for-hubspot/dogdgmomajhncdopjdijiabedklfampi

**Comment by DaKingKong** [comment]
Hi @Ruba85 The one you are using is the community version extension. We do have an official with better support and quality like what embbnux posted above  https://chrome.google.com/webstore/detail/ringcentral-for-hubspot/dogdgmomajhncdopjdijiabedklfampi 

The community one and official one have slight differences on their features. So please check if it suffices your use cases

**Comment by Ruba85** [comment]
Ok thank you we will try this one https://chrome.google.com/webstore/detail/ringcentral-for-hubspot/dogdgmomajhncdopjdijiabedklfampi
