### ISSUE TITLE
 V 7.10.4 is not compatible with manifest V3

### ISSUE THREAD

**Issue by NestorCanto** [ringcentral/hubspot-embeddable-ringcentral-phone#305]
The latest version of the code is not compatible with manifest v3, is there some plans to update the current code to make it compatible?

Seems that soon the older manifest version will stop working
![Screenshot_5](https://user-images.githubusercontent.com/57408554/204057762-88789b13-c574-4e9e-bec9-9e0e2d548bf1.png)

**Comment by CoCraig** [comment]
Hello @NestorCanto. Unfortunately this RC Labs chrome extension will not be upgraded to support Manifest v3.  Please use our official integration instead which is able to support manifest v3.
https://chrome.google.com/webstore/detail/ringcentral-for-hubspot/dogdgmomajhncdopjdijiabedklfampi

**Comment by NestorCanto** [comment]
Thanks for the info @CoCraig!
