### ISSUE TITLE
HubSpot contacts not appearing in RingCentral phone widget

### ISSUE THREAD

**Issue by bjsvec** [ringcentral/hubspot-embeddable-ringcentral-phone#96]
I'll share a series of screenshots that should demonstrate, but basically After launching Chrome and loading HubSpot I authorize, choose HubSpot account and then look under contacts, but none show up.

![screen shot 2018-10-11 at 5 02 17 pm](https://user-images.githubusercontent.com/43792275/46840429-d8fc0f00-cd77-11e8-8b0e-57351062e4a8.png)

![screen shot 2018-10-11 at 5 02 29 pm](https://user-images.githubusercontent.com/43792275/46840438-e44f3a80-cd77-11e8-8952-d20b3fb03ab2.png)

![screen shot 2018-10-11 at 5 02 41 pm](https://user-images.githubusercontent.com/43792275/46840448-eaddb200-cd77-11e8-95fb-70f2c388e9cb.png)

![screen shot 2018-10-11 at 5 02 51 pm](https://user-images.githubusercontent.com/43792275/46840458-f204c000-cd77-11e8-8c03-e9b07774f607.png)

![screen shot 2018-10-11 at 5 04 13 pm](https://user-images.githubusercontent.com/43792275/46840465-fe891880-cd77-11e8-88f8-641bee0a7cea.png)

**Comment by zxdong262** [comment]
Hi, @bjsvec 

Could you post all console logs here? The log may give some hint.

**Comment by bjsvec** [comment]
Let me know if these are what you are after.  From Chrome console copy/pasted.

It worked one time after closing and restarting browser so I have two logs to compare.



[did NOT show HubSpot contacts.txt](https://github.com/zxdong262/hubspot-embeddable-ringcentral-phone/files/2471248/did.NOT.show.HubSpot.contacts.txt)
[DID show HubSpot contacts.txt](https://github.com/zxdong262/hubspot-embeddable-ringcentral-phone/files/2471249/DID.show.HubSpot.contacts.txt)

**Comment by bjsvec** [comment]
Log when it worked after browser start.

[DID show HubSpot contacts.txt](https://github.com/zxdong262/hubspot-embeddable-ringcentral-phone/files/2471266/DID.show.HubSpot.contacts.txt)

**Comment by zxdong262** [comment]
Thank you, @bjsvec 

I will try to find out the problem.

**Comment by zxdong262** [comment]
Hi, @bjsvec 

Tried some more situation(logout all etc), can not reproduce the bug, can you give some possible steps to reproduce the bug?

**Comment by bjsvec** [comment]
It's been intermittent for me.  Here is a third condition when it looks like a list of my HubSpot contacts are there, but I know they are not.  https://youtu.be/CZPA05XH7ew

I'll post again when I catch it not showing the contact list at all.

**Comment by bjsvec** [comment]
All I did was refresh browser window and try again and this time it failed as I originally described.  Somehow it still synced the call records.  Three times per call it seems though.  A separate issue perhaps with that part.  
https://youtu.be/jECbic1rBHo

**Comment by zxdong262** [comment]
Hi, @bjsvec 
I fixed the three time sync bug, and released new versions, but still can not reproduce not showing contact list bug, might related to the account I use I guess, I may try get some other test account.

**Comment by bjsvec** [comment]
Well done and thank you.  I'll keep an eye on the not showing contact list bug and see if I can figure out how to reproduce it.

**Comment by zxdong262** [comment]
Close it now, feel free to submit another one.
